// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "dct_dct_1d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dct_dct_1d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dct_dct_1d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> dct_dct_1d::ap_ST_st1_fsm_0 = "1";
const sc_lv<4> dct_dct_1d::ap_ST_st2_fsm_1 = "10";
const sc_lv<4> dct_dct_1d::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<4> dct_dct_1d::ap_ST_st6_fsm_3 = "1000";
const bool dct_dct_1d::ap_true = true;
const sc_lv<32> dct_dct_1d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dct_dct_1d::ap_const_lv1_1 = "1";
const sc_lv<32> dct_dct_1d::ap_const_lv32_1 = "1";
const sc_lv<1> dct_dct_1d::ap_const_lv1_0 = "0";
const sc_lv<32> dct_dct_1d::ap_const_lv32_2 = "10";
const sc_lv<4> dct_dct_1d::ap_const_lv4_0 = "0000";
const sc_lv<32> dct_dct_1d::ap_const_lv32_3 = "11";
const sc_lv<3> dct_dct_1d::ap_const_lv3_0 = "000";
const sc_lv<4> dct_dct_1d::ap_const_lv4_8 = "1000";
const sc_lv<4> dct_dct_1d::ap_const_lv4_1 = "1";
const sc_lv<29> dct_dct_1d::ap_const_lv29_1000 = "1000000000000";
const sc_lv<32> dct_dct_1d::ap_const_lv32_D = "1101";
const sc_lv<32> dct_dct_1d::ap_const_lv32_1C = "11100";

dct_dct_1d::dct_dct_1d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dct_coeff_table_U = new dct_dct_1d_dct_coeff_table("dct_coeff_table_U");
    dct_coeff_table_U->clk(ap_clk);
    dct_coeff_table_U->reset(ap_rst);
    dct_coeff_table_U->address0(dct_coeff_table_address0);
    dct_coeff_table_U->ce0(dct_coeff_table_ce0);
    dct_coeff_table_U->q0(dct_coeff_table_q0);
    dct_mac_muladd_16s_15s_32ns_32_1_U0 = new dct_mac_muladd_16s_15s_32ns_32_1<1,1,16,15,32,32>("dct_mac_muladd_16s_15s_32ns_32_1_U0");
    dct_mac_muladd_16s_15s_32ns_32_1_U0->din0(grp_fu_262_p0);
    dct_mac_muladd_16s_15s_32ns_32_1_U0->din1(grp_fu_262_p1);
    dct_mac_muladd_16s_15s_32ns_32_1_U0->din2(grp_fu_262_p2);
    dct_mac_muladd_16s_15s_32ns_32_1_U0->dout(grp_fu_262_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( exitcond1_fu_161_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond1_fu_161_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_121);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_67);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_bdd_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_22 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_67 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_3);
    sensitive << ( ap_sig_bdd_121 );

    SC_METHOD(thread_dct_coeff_table_addr6_cast_fu_181_p1);
    sensitive << ( tmp_7_fu_173_p3 );

    SC_METHOD(thread_dct_coeff_table_addr7_fu_201_p2);
    sensitive << ( dct_coeff_table_addr6_cast_reg_289 );
    sensitive << ( tmp_6_trn5_cast_fu_197_p1 );

    SC_METHOD(thread_dct_coeff_table_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_13_fu_206_p1 );

    SC_METHOD(thread_dct_coeff_table_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_dst_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );
    sensitive << ( tmp_12_fu_257_p1 );

    SC_METHOD(thread_dst_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );

    SC_METHOD(thread_dst_d0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );
    sensitive << ( tmp_2_fu_231_p2 );

    SC_METHOD(thread_dst_we0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_3 );

    SC_METHOD(thread_exitcond1_fu_161_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( k_reg_102 );

    SC_METHOD(thread_exitcond_fu_185_p2);
    sensitive << ( n_reg_114 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_grp_fu_262_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_294_pp0_it1 );
    sensitive << ( src_load_reg_318 );

    SC_METHOD(thread_grp_fu_262_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_294_pp0_it1 );
    sensitive << ( dct_coeff_table_load_reg_313 );

    SC_METHOD(thread_grp_fu_262_p2);
    sensitive << ( tmp1_reg_125 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_reg_294_pp0_it1 );

    SC_METHOD(thread_k_1_fu_167_p2);
    sensitive << ( k_reg_102 );

    SC_METHOD(thread_n_1_fu_191_p2);
    sensitive << ( n_reg_114 );

    SC_METHOD(thread_p_addr1_fu_211_p2);
    sensitive << ( p_addr_cast_reg_270 );
    sensitive << ( tmp_6_trn5_cast_fu_197_p1 );

    SC_METHOD(thread_p_addr2_cast_fu_157_p1);
    sensitive << ( tmp_6_fu_149_p3 );

    SC_METHOD(thread_p_addr3_fu_252_p2);
    sensitive << ( p_addr2_cast_reg_275 );
    sensitive << ( tmp_trn_cast_fu_248_p1 );

    SC_METHOD(thread_p_addr_cast_fu_145_p1);
    sensitive << ( tmp_fu_137_p3 );

    SC_METHOD(thread_src_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( tmp_14_fu_216_p1 );

    SC_METHOD(thread_src_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_tmp_10_fu_227_p1);
    sensitive << ( tmp1_reg_125 );

    SC_METHOD(thread_tmp_12_fu_257_p1);
    sensitive << ( p_addr3_fu_252_p2 );

    SC_METHOD(thread_tmp_13_fu_206_p1);
    sensitive << ( dct_coeff_table_addr7_fu_201_p2 );

    SC_METHOD(thread_tmp_14_fu_216_p1);
    sensitive << ( p_addr1_fu_211_p2 );

    SC_METHOD(thread_tmp_2_fu_231_p2);
    sensitive << ( tmp_10_fu_227_p1 );

    SC_METHOD(thread_tmp_6_fu_149_p3);
    sensitive << ( tmp_11 );

    SC_METHOD(thread_tmp_6_trn5_cast_fu_197_p1);
    sensitive << ( n_reg_114 );

    SC_METHOD(thread_tmp_7_fu_173_p3);
    sensitive << ( k_reg_102 );

    SC_METHOD(thread_tmp_fu_137_p3);
    sensitive << ( tmp_1 );

    SC_METHOD(thread_tmp_trn_cast_fu_248_p1);
    sensitive << ( k_reg_102 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_161_p2 );
    sensitive << ( exitcond_fu_185_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it2 );

    ap_CS_fsm = "0001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dct_dct_1d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, src_address0, "(port)src_address0");
    sc_trace(mVcdFile, src_ce0, "(port)src_ce0");
    sc_trace(mVcdFile, src_q0, "(port)src_q0");
    sc_trace(mVcdFile, tmp_1, "(port)tmp_1");
    sc_trace(mVcdFile, dst_address0, "(port)dst_address0");
    sc_trace(mVcdFile, dst_ce0, "(port)dst_ce0");
    sc_trace(mVcdFile, dst_we0, "(port)dst_we0");
    sc_trace(mVcdFile, dst_d0, "(port)dst_d0");
    sc_trace(mVcdFile, tmp_11, "(port)tmp_11");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_22, "ap_sig_bdd_22");
    sc_trace(mVcdFile, dct_coeff_table_address0, "dct_coeff_table_address0");
    sc_trace(mVcdFile, dct_coeff_table_ce0, "dct_coeff_table_ce0");
    sc_trace(mVcdFile, dct_coeff_table_q0, "dct_coeff_table_q0");
    sc_trace(mVcdFile, n_reg_114, "n_reg_114");
    sc_trace(mVcdFile, tmp1_reg_125, "tmp1_reg_125");
    sc_trace(mVcdFile, p_addr_cast_fu_145_p1, "p_addr_cast_fu_145_p1");
    sc_trace(mVcdFile, p_addr_cast_reg_270, "p_addr_cast_reg_270");
    sc_trace(mVcdFile, p_addr2_cast_fu_157_p1, "p_addr2_cast_fu_157_p1");
    sc_trace(mVcdFile, p_addr2_cast_reg_275, "p_addr2_cast_reg_275");
    sc_trace(mVcdFile, exitcond1_fu_161_p2, "exitcond1_fu_161_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_67, "ap_sig_bdd_67");
    sc_trace(mVcdFile, k_1_fu_167_p2, "k_1_fu_167_p2");
    sc_trace(mVcdFile, k_1_reg_284, "k_1_reg_284");
    sc_trace(mVcdFile, dct_coeff_table_addr6_cast_fu_181_p1, "dct_coeff_table_addr6_cast_fu_181_p1");
    sc_trace(mVcdFile, dct_coeff_table_addr6_cast_reg_289, "dct_coeff_table_addr6_cast_reg_289");
    sc_trace(mVcdFile, exitcond_fu_185_p2, "exitcond_fu_185_p2");
    sc_trace(mVcdFile, exitcond_reg_294, "exitcond_reg_294");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_83, "ap_sig_bdd_83");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_reg_294_pp0_it1, "ap_reg_ppstg_exitcond_reg_294_pp0_it1");
    sc_trace(mVcdFile, n_1_fu_191_p2, "n_1_fu_191_p2");
    sc_trace(mVcdFile, dct_coeff_table_load_reg_313, "dct_coeff_table_load_reg_313");
    sc_trace(mVcdFile, src_load_reg_318, "src_load_reg_318");
    sc_trace(mVcdFile, grp_fu_262_p3, "grp_fu_262_p3");
    sc_trace(mVcdFile, k_reg_102, "k_reg_102");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_3, "ap_sig_cseq_ST_st6_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_121, "ap_sig_bdd_121");
    sc_trace(mVcdFile, tmp_13_fu_206_p1, "tmp_13_fu_206_p1");
    sc_trace(mVcdFile, tmp_14_fu_216_p1, "tmp_14_fu_216_p1");
    sc_trace(mVcdFile, tmp_12_fu_257_p1, "tmp_12_fu_257_p1");
    sc_trace(mVcdFile, tmp_fu_137_p3, "tmp_fu_137_p3");
    sc_trace(mVcdFile, tmp_6_fu_149_p3, "tmp_6_fu_149_p3");
    sc_trace(mVcdFile, tmp_7_fu_173_p3, "tmp_7_fu_173_p3");
    sc_trace(mVcdFile, tmp_6_trn5_cast_fu_197_p1, "tmp_6_trn5_cast_fu_197_p1");
    sc_trace(mVcdFile, dct_coeff_table_addr7_fu_201_p2, "dct_coeff_table_addr7_fu_201_p2");
    sc_trace(mVcdFile, p_addr1_fu_211_p2, "p_addr1_fu_211_p2");
    sc_trace(mVcdFile, tmp_10_fu_227_p1, "tmp_10_fu_227_p1");
    sc_trace(mVcdFile, tmp_2_fu_231_p2, "tmp_2_fu_231_p2");
    sc_trace(mVcdFile, tmp_trn_cast_fu_248_p1, "tmp_trn_cast_fu_248_p1");
    sc_trace(mVcdFile, p_addr3_fu_252_p2, "p_addr3_fu_252_p2");
    sc_trace(mVcdFile, grp_fu_262_p0, "grp_fu_262_p0");
    sc_trace(mVcdFile, grp_fu_262_p1, "grp_fu_262_p1");
    sc_trace(mVcdFile, grp_fu_262_p2, "grp_fu_262_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dct_dct_1d::~dct_dct_1d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dct_coeff_table_U;
    delete dct_mac_muladd_16s_15s_32ns_32_1_U0;
}

void dct_dct_1d::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read())) {
        k_reg_102 = k_1_reg_284.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        k_reg_102 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read()))) {
        n_reg_114 = n_1_fu_191_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
        n_reg_114 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_reg_294_pp0_it1.read()))) {
        tmp1_reg_125 = grp_fu_262_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
        tmp1_reg_125 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read())) {
        ap_reg_ppstg_exitcond_reg_294_pp0_it1 = exitcond_reg_294.read();
        exitcond_reg_294 = exitcond_fu_185_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
        dct_coeff_table_addr6_cast_reg_289 = dct_coeff_table_addr6_cast_fu_181_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_294.read()))) {
        dct_coeff_table_load_reg_313 = dct_coeff_table_q0.read();
        src_load_reg_318 = src_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        k_1_reg_284 = k_1_fu_167_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        p_addr2_cast_reg_275 = p_addr2_cast_fu_157_p1.read();
        p_addr_cast_reg_270 = p_addr_cast_fu_145_p1.read();
    }
}

void dct_dct_1d::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_sig_bdd_121() {
    ap_sig_bdd_121 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dct_dct_1d::thread_ap_sig_bdd_22() {
    ap_sig_bdd_22 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dct_dct_1d::thread_ap_sig_bdd_67() {
    ap_sig_bdd_67 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dct_dct_1d::thread_ap_sig_bdd_83() {
    ap_sig_bdd_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dct_dct_1d::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_bdd_83.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_22.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_67.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_ap_sig_cseq_ST_st6_fsm_3() {
    if (ap_sig_bdd_121.read()) {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_3 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_dct_coeff_table_addr6_cast_fu_181_p1() {
    dct_coeff_table_addr6_cast_fu_181_p1 = esl_zext<8,7>(tmp_7_fu_173_p3.read());
}

void dct_dct_1d::thread_dct_coeff_table_addr7_fu_201_p2() {
    dct_coeff_table_addr7_fu_201_p2 = (!tmp_6_trn5_cast_fu_197_p1.read().is_01() || !dct_coeff_table_addr6_cast_reg_289.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_6_trn5_cast_fu_197_p1.read()) + sc_biguint<8>(dct_coeff_table_addr6_cast_reg_289.read()));
}

void dct_dct_1d::thread_dct_coeff_table_address0() {
    dct_coeff_table_address0 =  (sc_lv<6>) (tmp_13_fu_206_p1.read());
}

void dct_dct_1d::thread_dct_coeff_table_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        dct_coeff_table_ce0 = ap_const_logic_1;
    } else {
        dct_coeff_table_ce0 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_dst_address0() {
    dst_address0 =  (sc_lv<6>) (tmp_12_fu_257_p1.read());
}

void dct_dct_1d::thread_dst_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read())) {
        dst_ce0 = ap_const_logic_1;
    } else {
        dst_ce0 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_dst_d0() {
    dst_d0 = tmp_2_fu_231_p2.read().range(28, 13);
}

void dct_dct_1d::thread_dst_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_3.read()))) {
        dst_we0 = ap_const_logic_1;
    } else {
        dst_we0 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_exitcond1_fu_161_p2() {
    exitcond1_fu_161_p2 = (!k_reg_102.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(k_reg_102.read() == ap_const_lv4_8);
}

void dct_dct_1d::thread_exitcond_fu_185_p2() {
    exitcond_fu_185_p2 = (!n_reg_114.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(n_reg_114.read() == ap_const_lv4_8);
}

void dct_dct_1d::thread_grp_fu_262_p0() {
    grp_fu_262_p0 = src_load_reg_318.read();
}

void dct_dct_1d::thread_grp_fu_262_p1() {
    grp_fu_262_p1 = dct_coeff_table_load_reg_313.read();
}

void dct_dct_1d::thread_grp_fu_262_p2() {
    grp_fu_262_p2 = tmp1_reg_125.read();
}

void dct_dct_1d::thread_k_1_fu_167_p2() {
    k_1_fu_167_p2 = (!k_reg_102.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(k_reg_102.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_dct_1d::thread_n_1_fu_191_p2() {
    n_1_fu_191_p2 = (!n_reg_114.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(n_reg_114.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dct_dct_1d::thread_p_addr1_fu_211_p2() {
    p_addr1_fu_211_p2 = (!tmp_6_trn5_cast_fu_197_p1.read().is_01() || !p_addr_cast_reg_270.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_6_trn5_cast_fu_197_p1.read()) + sc_biguint<8>(p_addr_cast_reg_270.read()));
}

void dct_dct_1d::thread_p_addr2_cast_fu_157_p1() {
    p_addr2_cast_fu_157_p1 = esl_zext<8,7>(tmp_6_fu_149_p3.read());
}

void dct_dct_1d::thread_p_addr3_fu_252_p2() {
    p_addr3_fu_252_p2 = (!tmp_trn_cast_fu_248_p1.read().is_01() || !p_addr2_cast_reg_275.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_trn_cast_fu_248_p1.read()) + sc_biguint<8>(p_addr2_cast_reg_275.read()));
}

void dct_dct_1d::thread_p_addr_cast_fu_145_p1() {
    p_addr_cast_fu_145_p1 = esl_zext<8,7>(tmp_fu_137_p3.read());
}

void dct_dct_1d::thread_src_address0() {
    src_address0 =  (sc_lv<6>) (tmp_14_fu_216_p1.read());
}

void dct_dct_1d::thread_src_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()))) {
        src_ce0 = ap_const_logic_1;
    } else {
        src_ce0 = ap_const_logic_0;
    }
}

void dct_dct_1d::thread_tmp_10_fu_227_p1() {
    tmp_10_fu_227_p1 = tmp1_reg_125.read().range(29-1, 0);
}

void dct_dct_1d::thread_tmp_12_fu_257_p1() {
    tmp_12_fu_257_p1 = esl_zext<64,8>(p_addr3_fu_252_p2.read());
}

void dct_dct_1d::thread_tmp_13_fu_206_p1() {
    tmp_13_fu_206_p1 = esl_zext<64,8>(dct_coeff_table_addr7_fu_201_p2.read());
}

void dct_dct_1d::thread_tmp_14_fu_216_p1() {
    tmp_14_fu_216_p1 = esl_zext<64,8>(p_addr1_fu_211_p2.read());
}

void dct_dct_1d::thread_tmp_2_fu_231_p2() {
    tmp_2_fu_231_p2 = (!ap_const_lv29_1000.is_01() || !tmp_10_fu_227_p1.read().is_01())? sc_lv<29>(): (sc_biguint<29>(ap_const_lv29_1000) + sc_biguint<29>(tmp_10_fu_227_p1.read()));
}

void dct_dct_1d::thread_tmp_6_fu_149_p3() {
    tmp_6_fu_149_p3 = esl_concat<4,3>(tmp_11.read(), ap_const_lv3_0);
}

void dct_dct_1d::thread_tmp_6_trn5_cast_fu_197_p1() {
    tmp_6_trn5_cast_fu_197_p1 = esl_zext<8,4>(n_reg_114.read());
}

void dct_dct_1d::thread_tmp_7_fu_173_p3() {
    tmp_7_fu_173_p3 = esl_concat<4,3>(k_reg_102.read(), ap_const_lv3_0);
}

void dct_dct_1d::thread_tmp_fu_137_p3() {
    tmp_fu_137_p3 = esl_concat<4,3>(tmp_1.read(), ap_const_lv3_0);
}

void dct_dct_1d::thread_tmp_trn_cast_fu_248_p1() {
    tmp_trn_cast_fu_248_p1 = esl_zext<8,4>(k_reg_102.read());
}

void dct_dct_1d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_161_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_185_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st6_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

