:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2015.2
:: Copyright (C) 2015 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

C:/opt/winprog/Xilinx/Vivado_HLS/2015.2/../../Vivado/2015.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7k160tfbg484-2 ../xilinx_com_hls_fir_1_0.zip
