#pragma line 1 "adders.c" ::: -10
#pragma line 1 "adders.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/opt/winprog/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 280 "C:/opt/winprog/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 7 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "adders.c" 2 ::: 183
#pragma line 1 "./adders.h" 1 ::: 230
#pragma line 47 "adders.c" 2 ::: 280
