// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct,hls_ip_2015_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k160tfbg484-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.930000,HLS_SYN_LAT=508,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=8,HLS_SYN_FF=1243,HLS_SYN_LUT=634}" *)

module dct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b1;
parameter    ap_ST_st2_fsm_1 = 6'b10;
parameter    ap_ST_st3_fsm_2 = 6'b100;
parameter    ap_ST_st4_fsm_3 = 6'b1000;
parameter    ap_ST_pp0_stg0_fsm_4 = 6'b10000;
parameter    ap_ST_st7_fsm_5 = 6'b100000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm = 6'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_22;
reg   [6:0] indvar_flatten_reg_134;
reg   [3:0] r_i_reg_145;
reg   [3:0] c_i_reg_156;
wire   [0:0] exitcond_flatten_fu_218_p2;
reg   [0:0] exitcond_flatten_reg_317;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_4;
reg    ap_sig_bdd_55;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
wire   [6:0] indvar_flatten_next_fu_224_p2;
wire   [3:0] r_i_mid2_fu_250_p3;
reg   [3:0] r_i_mid2_reg_326;
wire   [5:0] tmp_9_i_fu_301_p2;
reg   [5:0] tmp_9_i_reg_336;
wire   [3:0] c_fu_307_p2;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_81;
wire    grp_dct_dct_2d_fu_167_ap_done;
reg   [2:0] buf_2d_in_0_address0;
reg    buf_2d_in_0_ce0;
reg    buf_2d_in_0_we0;
wire   [15:0] buf_2d_in_0_d0;
wire   [15:0] buf_2d_in_0_q0;
reg   [2:0] buf_2d_in_1_address0;
reg    buf_2d_in_1_ce0;
reg    buf_2d_in_1_we0;
wire   [15:0] buf_2d_in_1_d0;
wire   [15:0] buf_2d_in_1_q0;
reg   [2:0] buf_2d_in_2_address0;
reg    buf_2d_in_2_ce0;
reg    buf_2d_in_2_we0;
wire   [15:0] buf_2d_in_2_d0;
wire   [15:0] buf_2d_in_2_q0;
reg   [2:0] buf_2d_in_3_address0;
reg    buf_2d_in_3_ce0;
reg    buf_2d_in_3_we0;
wire   [15:0] buf_2d_in_3_d0;
wire   [15:0] buf_2d_in_3_q0;
reg   [2:0] buf_2d_in_4_address0;
reg    buf_2d_in_4_ce0;
reg    buf_2d_in_4_we0;
wire   [15:0] buf_2d_in_4_d0;
wire   [15:0] buf_2d_in_4_q0;
reg   [2:0] buf_2d_in_5_address0;
reg    buf_2d_in_5_ce0;
reg    buf_2d_in_5_we0;
wire   [15:0] buf_2d_in_5_d0;
wire   [15:0] buf_2d_in_5_q0;
reg   [2:0] buf_2d_in_6_address0;
reg    buf_2d_in_6_ce0;
reg    buf_2d_in_6_we0;
wire   [15:0] buf_2d_in_6_d0;
wire   [15:0] buf_2d_in_6_q0;
reg   [2:0] buf_2d_in_7_address0;
reg    buf_2d_in_7_ce0;
reg    buf_2d_in_7_we0;
wire   [15:0] buf_2d_in_7_d0;
wire   [15:0] buf_2d_in_7_q0;
reg   [5:0] buf_2d_out_address0;
reg    buf_2d_out_ce0;
reg    buf_2d_out_we0;
wire   [15:0] buf_2d_out_d0;
wire   [15:0] buf_2d_out_q0;
wire    grp_dct_dct_2d_fu_167_ap_start;
wire    grp_dct_dct_2d_fu_167_ap_idle;
wire    grp_dct_dct_2d_fu_167_ap_ready;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_0_address0;
wire    grp_dct_dct_2d_fu_167_in_block_0_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_0_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_1_address0;
wire    grp_dct_dct_2d_fu_167_in_block_1_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_1_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_2_address0;
wire    grp_dct_dct_2d_fu_167_in_block_2_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_2_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_3_address0;
wire    grp_dct_dct_2d_fu_167_in_block_3_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_3_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_4_address0;
wire    grp_dct_dct_2d_fu_167_in_block_4_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_4_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_5_address0;
wire    grp_dct_dct_2d_fu_167_in_block_5_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_5_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_6_address0;
wire    grp_dct_dct_2d_fu_167_in_block_6_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_6_q0;
wire   [2:0] grp_dct_dct_2d_fu_167_in_block_7_address0;
wire    grp_dct_dct_2d_fu_167_in_block_7_ce0;
wire   [15:0] grp_dct_dct_2d_fu_167_in_block_7_q0;
wire   [5:0] grp_dct_dct_2d_fu_167_out_block_address0;
wire    grp_dct_dct_2d_fu_167_out_block_ce0;
wire    grp_dct_dct_2d_fu_167_out_block_we0;
wire   [15:0] grp_dct_dct_2d_fu_167_out_block_d0;
wire    grp_dct_read_data_fu_196_ap_start;
wire    grp_dct_read_data_fu_196_ap_done;
wire    grp_dct_read_data_fu_196_ap_idle;
wire    grp_dct_read_data_fu_196_ap_ready;
wire   [5:0] grp_dct_read_data_fu_196_input_r_address0;
wire    grp_dct_read_data_fu_196_input_r_ce0;
wire   [15:0] grp_dct_read_data_fu_196_input_r_q0;
wire   [2:0] grp_dct_read_data_fu_196_buf_0_address0;
wire    grp_dct_read_data_fu_196_buf_0_ce0;
wire    grp_dct_read_data_fu_196_buf_0_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_0_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_1_address0;
wire    grp_dct_read_data_fu_196_buf_1_ce0;
wire    grp_dct_read_data_fu_196_buf_1_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_1_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_2_address0;
wire    grp_dct_read_data_fu_196_buf_2_ce0;
wire    grp_dct_read_data_fu_196_buf_2_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_2_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_3_address0;
wire    grp_dct_read_data_fu_196_buf_3_ce0;
wire    grp_dct_read_data_fu_196_buf_3_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_3_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_4_address0;
wire    grp_dct_read_data_fu_196_buf_4_ce0;
wire    grp_dct_read_data_fu_196_buf_4_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_4_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_5_address0;
wire    grp_dct_read_data_fu_196_buf_5_ce0;
wire    grp_dct_read_data_fu_196_buf_5_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_5_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_6_address0;
wire    grp_dct_read_data_fu_196_buf_6_ce0;
wire    grp_dct_read_data_fu_196_buf_6_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_6_d0;
wire   [2:0] grp_dct_read_data_fu_196_buf_7_address0;
wire    grp_dct_read_data_fu_196_buf_7_ce0;
wire    grp_dct_read_data_fu_196_buf_7_we0;
wire   [15:0] grp_dct_read_data_fu_196_buf_7_d0;
reg   [3:0] r_i_phi_fu_149_p4;
reg    grp_dct_dct_2d_fu_167_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_262;
reg    grp_dct_read_data_fu_196_ap_start_ap_start_reg = 1'b0;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_338;
wire   [63:0] tmp_2_fu_296_p1;
wire   [63:0] tmp_3_i_fu_313_p1;
wire   [0:0] exitcond_i5_fu_230_p2;
wire   [3:0] r3_fu_244_p2;
wire   [2:0] tmp_fu_258_p1;
wire   [3:0] c_i_mid2_fu_236_p3;
wire   [6:0] tmp_1_fu_278_p3;
wire   [7:0] p_addr_cast_fu_286_p1;
wire   [7:0] tmp_8_i_trn_cast_fu_274_p1;
wire   [7:0] p_addr2_fu_290_p2;
wire   [5:0] c_i_cast2_fu_270_p1;
wire   [5:0] tmp_i_fu_262_p3;
reg    ap_sig_cseq_ST_st7_fsm_5;
reg    ap_sig_bdd_411;
reg   [5:0] ap_NS_fsm;


dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_0_address0 ),
    .ce0( buf_2d_in_0_ce0 ),
    .we0( buf_2d_in_0_we0 ),
    .d0( buf_2d_in_0_d0 ),
    .q0( buf_2d_in_0_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_1_address0 ),
    .ce0( buf_2d_in_1_ce0 ),
    .we0( buf_2d_in_1_we0 ),
    .d0( buf_2d_in_1_d0 ),
    .q0( buf_2d_in_1_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_2_address0 ),
    .ce0( buf_2d_in_2_ce0 ),
    .we0( buf_2d_in_2_we0 ),
    .d0( buf_2d_in_2_d0 ),
    .q0( buf_2d_in_2_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_3_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_3_address0 ),
    .ce0( buf_2d_in_3_ce0 ),
    .we0( buf_2d_in_3_we0 ),
    .d0( buf_2d_in_3_d0 ),
    .q0( buf_2d_in_3_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_4_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_4_address0 ),
    .ce0( buf_2d_in_4_ce0 ),
    .we0( buf_2d_in_4_we0 ),
    .d0( buf_2d_in_4_d0 ),
    .q0( buf_2d_in_4_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_5_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_5_address0 ),
    .ce0( buf_2d_in_5_ce0 ),
    .we0( buf_2d_in_5_we0 ),
    .d0( buf_2d_in_5_d0 ),
    .q0( buf_2d_in_5_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_6_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_6_address0 ),
    .ce0( buf_2d_in_6_ce0 ),
    .we0( buf_2d_in_6_we0 ),
    .d0( buf_2d_in_6_d0 ),
    .q0( buf_2d_in_6_q0 )
);

dct_dct_2d_col_inbuf_0 #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
buf_2d_in_7_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_in_7_address0 ),
    .ce0( buf_2d_in_7_ce0 ),
    .we0( buf_2d_in_7_we0 ),
    .d0( buf_2d_in_7_d0 ),
    .q0( buf_2d_in_7_q0 )
);

dct_dct_2d_row_outbuf #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_out_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( buf_2d_out_address0 ),
    .ce0( buf_2d_out_ce0 ),
    .we0( buf_2d_out_we0 ),
    .d0( buf_2d_out_d0 ),
    .q0( buf_2d_out_q0 )
);

dct_dct_2d grp_dct_dct_2d_fu_167(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_dct_dct_2d_fu_167_ap_start ),
    .ap_done( grp_dct_dct_2d_fu_167_ap_done ),
    .ap_idle( grp_dct_dct_2d_fu_167_ap_idle ),
    .ap_ready( grp_dct_dct_2d_fu_167_ap_ready ),
    .in_block_0_address0( grp_dct_dct_2d_fu_167_in_block_0_address0 ),
    .in_block_0_ce0( grp_dct_dct_2d_fu_167_in_block_0_ce0 ),
    .in_block_0_q0( grp_dct_dct_2d_fu_167_in_block_0_q0 ),
    .in_block_1_address0( grp_dct_dct_2d_fu_167_in_block_1_address0 ),
    .in_block_1_ce0( grp_dct_dct_2d_fu_167_in_block_1_ce0 ),
    .in_block_1_q0( grp_dct_dct_2d_fu_167_in_block_1_q0 ),
    .in_block_2_address0( grp_dct_dct_2d_fu_167_in_block_2_address0 ),
    .in_block_2_ce0( grp_dct_dct_2d_fu_167_in_block_2_ce0 ),
    .in_block_2_q0( grp_dct_dct_2d_fu_167_in_block_2_q0 ),
    .in_block_3_address0( grp_dct_dct_2d_fu_167_in_block_3_address0 ),
    .in_block_3_ce0( grp_dct_dct_2d_fu_167_in_block_3_ce0 ),
    .in_block_3_q0( grp_dct_dct_2d_fu_167_in_block_3_q0 ),
    .in_block_4_address0( grp_dct_dct_2d_fu_167_in_block_4_address0 ),
    .in_block_4_ce0( grp_dct_dct_2d_fu_167_in_block_4_ce0 ),
    .in_block_4_q0( grp_dct_dct_2d_fu_167_in_block_4_q0 ),
    .in_block_5_address0( grp_dct_dct_2d_fu_167_in_block_5_address0 ),
    .in_block_5_ce0( grp_dct_dct_2d_fu_167_in_block_5_ce0 ),
    .in_block_5_q0( grp_dct_dct_2d_fu_167_in_block_5_q0 ),
    .in_block_6_address0( grp_dct_dct_2d_fu_167_in_block_6_address0 ),
    .in_block_6_ce0( grp_dct_dct_2d_fu_167_in_block_6_ce0 ),
    .in_block_6_q0( grp_dct_dct_2d_fu_167_in_block_6_q0 ),
    .in_block_7_address0( grp_dct_dct_2d_fu_167_in_block_7_address0 ),
    .in_block_7_ce0( grp_dct_dct_2d_fu_167_in_block_7_ce0 ),
    .in_block_7_q0( grp_dct_dct_2d_fu_167_in_block_7_q0 ),
    .out_block_address0( grp_dct_dct_2d_fu_167_out_block_address0 ),
    .out_block_ce0( grp_dct_dct_2d_fu_167_out_block_ce0 ),
    .out_block_we0( grp_dct_dct_2d_fu_167_out_block_we0 ),
    .out_block_d0( grp_dct_dct_2d_fu_167_out_block_d0 )
);

dct_read_data grp_dct_read_data_fu_196(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_dct_read_data_fu_196_ap_start ),
    .ap_done( grp_dct_read_data_fu_196_ap_done ),
    .ap_idle( grp_dct_read_data_fu_196_ap_idle ),
    .ap_ready( grp_dct_read_data_fu_196_ap_ready ),
    .input_r_address0( grp_dct_read_data_fu_196_input_r_address0 ),
    .input_r_ce0( grp_dct_read_data_fu_196_input_r_ce0 ),
    .input_r_q0( grp_dct_read_data_fu_196_input_r_q0 ),
    .buf_0_address0( grp_dct_read_data_fu_196_buf_0_address0 ),
    .buf_0_ce0( grp_dct_read_data_fu_196_buf_0_ce0 ),
    .buf_0_we0( grp_dct_read_data_fu_196_buf_0_we0 ),
    .buf_0_d0( grp_dct_read_data_fu_196_buf_0_d0 ),
    .buf_1_address0( grp_dct_read_data_fu_196_buf_1_address0 ),
    .buf_1_ce0( grp_dct_read_data_fu_196_buf_1_ce0 ),
    .buf_1_we0( grp_dct_read_data_fu_196_buf_1_we0 ),
    .buf_1_d0( grp_dct_read_data_fu_196_buf_1_d0 ),
    .buf_2_address0( grp_dct_read_data_fu_196_buf_2_address0 ),
    .buf_2_ce0( grp_dct_read_data_fu_196_buf_2_ce0 ),
    .buf_2_we0( grp_dct_read_data_fu_196_buf_2_we0 ),
    .buf_2_d0( grp_dct_read_data_fu_196_buf_2_d0 ),
    .buf_3_address0( grp_dct_read_data_fu_196_buf_3_address0 ),
    .buf_3_ce0( grp_dct_read_data_fu_196_buf_3_ce0 ),
    .buf_3_we0( grp_dct_read_data_fu_196_buf_3_we0 ),
    .buf_3_d0( grp_dct_read_data_fu_196_buf_3_d0 ),
    .buf_4_address0( grp_dct_read_data_fu_196_buf_4_address0 ),
    .buf_4_ce0( grp_dct_read_data_fu_196_buf_4_ce0 ),
    .buf_4_we0( grp_dct_read_data_fu_196_buf_4_we0 ),
    .buf_4_d0( grp_dct_read_data_fu_196_buf_4_d0 ),
    .buf_5_address0( grp_dct_read_data_fu_196_buf_5_address0 ),
    .buf_5_ce0( grp_dct_read_data_fu_196_buf_5_ce0 ),
    .buf_5_we0( grp_dct_read_data_fu_196_buf_5_we0 ),
    .buf_5_d0( grp_dct_read_data_fu_196_buf_5_d0 ),
    .buf_6_address0( grp_dct_read_data_fu_196_buf_6_address0 ),
    .buf_6_ce0( grp_dct_read_data_fu_196_buf_6_ce0 ),
    .buf_6_we0( grp_dct_read_data_fu_196_buf_6_we0 ),
    .buf_6_d0( grp_dct_read_data_fu_196_buf_6_d0 ),
    .buf_7_address0( grp_dct_read_data_fu_196_buf_7_address0 ),
    .buf_7_ce0( grp_dct_read_data_fu_196_buf_7_ce0 ),
    .buf_7_we0( grp_dct_read_data_fu_196_buf_7_we0 ),
    .buf_7_d0( grp_dct_read_data_fu_196_buf_7_d0 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & ~(exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & ~(exitcond_flatten_fu_218_p2 == ap_const_lv1_0)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// grp_dct_dct_2d_fu_167_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_dct_dct_2d_fu_167_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_dct_dct_2d_fu_167_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            grp_dct_dct_2d_fu_167_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_dct_dct_2d_fu_167_ap_ready)) begin
            grp_dct_dct_2d_fu_167_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_dct_read_data_fu_196_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_dct_read_data_fu_196_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_dct_read_data_fu_196_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
            grp_dct_read_data_fu_196_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_dct_read_data_fu_196_ap_ready)) begin
            grp_dct_read_data_fu_196_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
        c_i_reg_156 <= c_fu_307_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done))) begin
        c_i_reg_156 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
        indvar_flatten_reg_134 <= indvar_flatten_next_fu_224_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done))) begin
        indvar_flatten_reg_134 <= ap_const_lv7_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_317 == ap_const_lv1_0))) begin
        r_i_reg_145 <= r_i_mid2_reg_326;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done))) begin
        r_i_reg_145 <= ap_const_lv4_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4)) begin
        exitcond_flatten_reg_317 <= exitcond_flatten_fu_218_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
        r_i_mid2_reg_326 <= r_i_mid2_fu_250_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
        tmp_9_i_reg_336 <= tmp_9_i_fu_301_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_sig_cseq_ST_st7_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5)) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st7_fsm_5)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st7_fsm_5)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_4 assign process. ///
always @ (ap_sig_bdd_55)
begin
    if (ap_sig_bdd_55) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_22)
begin
    if (ap_sig_bdd_22) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_338)
begin
    if (ap_sig_bdd_338) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_262)
begin
    if (ap_sig_bdd_262) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_81)
begin
    if (ap_sig_bdd_81) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_5 assign process. ///
always @ (ap_sig_bdd_411)
begin
    if (ap_sig_bdd_411) begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_5 = ap_const_logic_0;
    end
end

/// buf_2d_in_0_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_0_address0 or grp_dct_read_data_fu_196_buf_0_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_0_address0 = grp_dct_read_data_fu_196_buf_0_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_0_address0 = grp_dct_dct_2d_fu_167_in_block_0_address0;
    end else begin
        buf_2d_in_0_address0 = 'bx;
    end
end

/// buf_2d_in_0_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_0_ce0 or grp_dct_read_data_fu_196_buf_0_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_0_ce0 = grp_dct_read_data_fu_196_buf_0_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_0_ce0 = grp_dct_dct_2d_fu_167_in_block_0_ce0;
    end else begin
        buf_2d_in_0_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_0_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_0_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_0_we0 = grp_dct_read_data_fu_196_buf_0_we0;
    end else begin
        buf_2d_in_0_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_1_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_1_address0 or grp_dct_read_data_fu_196_buf_1_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_1_address0 = grp_dct_read_data_fu_196_buf_1_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_1_address0 = grp_dct_dct_2d_fu_167_in_block_1_address0;
    end else begin
        buf_2d_in_1_address0 = 'bx;
    end
end

/// buf_2d_in_1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_1_ce0 or grp_dct_read_data_fu_196_buf_1_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_1_ce0 = grp_dct_read_data_fu_196_buf_1_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_1_ce0 = grp_dct_dct_2d_fu_167_in_block_1_ce0;
    end else begin
        buf_2d_in_1_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_1_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_1_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_1_we0 = grp_dct_read_data_fu_196_buf_1_we0;
    end else begin
        buf_2d_in_1_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_2_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_2_address0 or grp_dct_read_data_fu_196_buf_2_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_2_address0 = grp_dct_read_data_fu_196_buf_2_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_2_address0 = grp_dct_dct_2d_fu_167_in_block_2_address0;
    end else begin
        buf_2d_in_2_address0 = 'bx;
    end
end

/// buf_2d_in_2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_2_ce0 or grp_dct_read_data_fu_196_buf_2_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_2_ce0 = grp_dct_read_data_fu_196_buf_2_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_2_ce0 = grp_dct_dct_2d_fu_167_in_block_2_ce0;
    end else begin
        buf_2d_in_2_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_2_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_2_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_2_we0 = grp_dct_read_data_fu_196_buf_2_we0;
    end else begin
        buf_2d_in_2_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_3_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_3_address0 or grp_dct_read_data_fu_196_buf_3_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_3_address0 = grp_dct_read_data_fu_196_buf_3_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_3_address0 = grp_dct_dct_2d_fu_167_in_block_3_address0;
    end else begin
        buf_2d_in_3_address0 = 'bx;
    end
end

/// buf_2d_in_3_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_3_ce0 or grp_dct_read_data_fu_196_buf_3_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_3_ce0 = grp_dct_read_data_fu_196_buf_3_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_3_ce0 = grp_dct_dct_2d_fu_167_in_block_3_ce0;
    end else begin
        buf_2d_in_3_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_3_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_3_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_3_we0 = grp_dct_read_data_fu_196_buf_3_we0;
    end else begin
        buf_2d_in_3_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_4_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_4_address0 or grp_dct_read_data_fu_196_buf_4_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_4_address0 = grp_dct_read_data_fu_196_buf_4_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_4_address0 = grp_dct_dct_2d_fu_167_in_block_4_address0;
    end else begin
        buf_2d_in_4_address0 = 'bx;
    end
end

/// buf_2d_in_4_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_4_ce0 or grp_dct_read_data_fu_196_buf_4_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_4_ce0 = grp_dct_read_data_fu_196_buf_4_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_4_ce0 = grp_dct_dct_2d_fu_167_in_block_4_ce0;
    end else begin
        buf_2d_in_4_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_4_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_4_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_4_we0 = grp_dct_read_data_fu_196_buf_4_we0;
    end else begin
        buf_2d_in_4_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_5_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_5_address0 or grp_dct_read_data_fu_196_buf_5_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_5_address0 = grp_dct_read_data_fu_196_buf_5_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_5_address0 = grp_dct_dct_2d_fu_167_in_block_5_address0;
    end else begin
        buf_2d_in_5_address0 = 'bx;
    end
end

/// buf_2d_in_5_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_5_ce0 or grp_dct_read_data_fu_196_buf_5_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_5_ce0 = grp_dct_read_data_fu_196_buf_5_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_5_ce0 = grp_dct_dct_2d_fu_167_in_block_5_ce0;
    end else begin
        buf_2d_in_5_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_5_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_5_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_5_we0 = grp_dct_read_data_fu_196_buf_5_we0;
    end else begin
        buf_2d_in_5_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_6_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_6_address0 or grp_dct_read_data_fu_196_buf_6_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_6_address0 = grp_dct_read_data_fu_196_buf_6_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_6_address0 = grp_dct_dct_2d_fu_167_in_block_6_address0;
    end else begin
        buf_2d_in_6_address0 = 'bx;
    end
end

/// buf_2d_in_6_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_6_ce0 or grp_dct_read_data_fu_196_buf_6_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_6_ce0 = grp_dct_read_data_fu_196_buf_6_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_6_ce0 = grp_dct_dct_2d_fu_167_in_block_6_ce0;
    end else begin
        buf_2d_in_6_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_6_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_6_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_6_we0 = grp_dct_read_data_fu_196_buf_6_we0;
    end else begin
        buf_2d_in_6_we0 = ap_const_logic_0;
    end
end

/// buf_2d_in_7_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_7_address0 or grp_dct_read_data_fu_196_buf_7_address0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_7_address0 = grp_dct_read_data_fu_196_buf_7_address0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_7_address0 = grp_dct_dct_2d_fu_167_in_block_7_address0;
    end else begin
        buf_2d_in_7_address0 = 'bx;
    end
end

/// buf_2d_in_7_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_in_block_7_ce0 or grp_dct_read_data_fu_196_buf_7_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_7_ce0 = grp_dct_read_data_fu_196_buf_7_ce0;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_in_7_ce0 = grp_dct_dct_2d_fu_167_in_block_7_ce0;
    end else begin
        buf_2d_in_7_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_in_7_we0 assign process. ///
always @ (grp_dct_read_data_fu_196_buf_7_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        buf_2d_in_7_we0 = grp_dct_read_data_fu_196_buf_7_we0;
    end else begin
        buf_2d_in_7_we0 = ap_const_logic_0;
    end
end

/// buf_2d_out_address0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_4 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_out_block_address0 or tmp_2_fu_296_p1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        buf_2d_out_address0 = tmp_2_fu_296_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_out_address0 = grp_dct_dct_2d_fu_167_out_block_address0;
    end else begin
        buf_2d_out_address0 = 'bx;
    end
end

/// buf_2d_out_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_4 or ap_reg_ppiten_pp0_it0 or ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_out_block_ce0)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0))) begin
        buf_2d_out_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_out_ce0 = grp_dct_dct_2d_fu_167_out_block_ce0;
    end else begin
        buf_2d_out_ce0 = ap_const_logic_0;
    end
end

/// buf_2d_out_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or grp_dct_dct_2d_fu_167_out_block_we0)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        buf_2d_out_we0 = grp_dct_dct_2d_fu_167_out_block_we0;
    end else begin
        buf_2d_out_we0 = ap_const_logic_0;
    end
end

/// input_r_ce0 assign process. ///
always @ (grp_dct_read_data_fu_196_input_r_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        input_r_ce0 = grp_dct_read_data_fu_196_input_r_ce0;
    end else begin
        input_r_ce0 = ap_const_logic_0;
    end
end

/// output_r_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_4 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1))) begin
        output_r_ce0 = ap_const_logic_1;
    end else begin
        output_r_ce0 = ap_const_logic_0;
    end
end

/// output_r_we0 assign process. ///
always @ (exitcond_flatten_reg_317 or ap_sig_cseq_ST_pp0_stg0_fsm_4 or ap_reg_ppiten_pp0_it1)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_317 == ap_const_lv1_0))) begin
        output_r_we0 = ap_const_logic_1;
    end else begin
        output_r_we0 = ap_const_logic_0;
    end
end

/// r_i_phi_fu_149_p4 assign process. ///
always @ (r_i_reg_145 or exitcond_flatten_reg_317 or ap_sig_cseq_ST_pp0_stg0_fsm_4 or ap_reg_ppiten_pp0_it1 or r_i_mid2_reg_326)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_4) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten_reg_317 == ap_const_lv1_0))) begin
        r_i_phi_fu_149_p4 = r_i_mid2_reg_326;
    end else begin
        r_i_phi_fu_149_p4 = r_i_reg_145;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or exitcond_flatten_fu_218_p2 or ap_reg_ppiten_pp0_it0 or grp_dct_dct_2d_fu_167_ap_done or grp_dct_read_data_fu_196_ap_done)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~(ap_const_logic_0 == grp_dct_read_data_fu_196_ap_done)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_st4_fsm_3;
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_logic_0 == grp_dct_dct_2d_fu_167_ap_done)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end
        end
        ap_ST_pp0_stg0_fsm_4 : 
        begin
            if (~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~(exitcond_flatten_fu_218_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_5;
            end
        end
        ap_ST_st7_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end


/// ap_sig_bdd_22 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_22 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_262 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_262 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_338 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_338 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_411 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_411 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_55 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_55 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_81 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_81 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end
assign buf_2d_in_0_d0 = grp_dct_read_data_fu_196_buf_0_d0;
assign buf_2d_in_1_d0 = grp_dct_read_data_fu_196_buf_1_d0;
assign buf_2d_in_2_d0 = grp_dct_read_data_fu_196_buf_2_d0;
assign buf_2d_in_3_d0 = grp_dct_read_data_fu_196_buf_3_d0;
assign buf_2d_in_4_d0 = grp_dct_read_data_fu_196_buf_4_d0;
assign buf_2d_in_5_d0 = grp_dct_read_data_fu_196_buf_5_d0;
assign buf_2d_in_6_d0 = grp_dct_read_data_fu_196_buf_6_d0;
assign buf_2d_in_7_d0 = grp_dct_read_data_fu_196_buf_7_d0;
assign buf_2d_out_d0 = grp_dct_dct_2d_fu_167_out_block_d0;
assign c_fu_307_p2 = (ap_const_lv4_1 + c_i_mid2_fu_236_p3);
assign c_i_cast2_fu_270_p1 = c_i_mid2_fu_236_p3;
assign c_i_mid2_fu_236_p3 = ((exitcond_i5_fu_230_p2[0:0]===1'b1)? ap_const_lv4_0: c_i_reg_156);
assign exitcond_flatten_fu_218_p2 = (indvar_flatten_reg_134 == ap_const_lv7_40? 1'b1: 1'b0);
assign exitcond_i5_fu_230_p2 = (c_i_reg_156 == ap_const_lv4_8? 1'b1: 1'b0);
assign grp_dct_dct_2d_fu_167_ap_start = grp_dct_dct_2d_fu_167_ap_start_ap_start_reg;
assign grp_dct_dct_2d_fu_167_in_block_0_q0 = buf_2d_in_0_q0;
assign grp_dct_dct_2d_fu_167_in_block_1_q0 = buf_2d_in_1_q0;
assign grp_dct_dct_2d_fu_167_in_block_2_q0 = buf_2d_in_2_q0;
assign grp_dct_dct_2d_fu_167_in_block_3_q0 = buf_2d_in_3_q0;
assign grp_dct_dct_2d_fu_167_in_block_4_q0 = buf_2d_in_4_q0;
assign grp_dct_dct_2d_fu_167_in_block_5_q0 = buf_2d_in_5_q0;
assign grp_dct_dct_2d_fu_167_in_block_6_q0 = buf_2d_in_6_q0;
assign grp_dct_dct_2d_fu_167_in_block_7_q0 = buf_2d_in_7_q0;
assign grp_dct_read_data_fu_196_ap_start = grp_dct_read_data_fu_196_ap_start_ap_start_reg;
assign grp_dct_read_data_fu_196_input_r_q0 = input_r_q0;
assign indvar_flatten_next_fu_224_p2 = (indvar_flatten_reg_134 + ap_const_lv7_1);
assign input_r_address0 = grp_dct_read_data_fu_196_input_r_address0;
assign output_r_address0 = tmp_3_i_fu_313_p1;
assign output_r_d0 = buf_2d_out_q0;
assign p_addr2_fu_290_p2 = (p_addr_cast_fu_286_p1 + tmp_8_i_trn_cast_fu_274_p1);
assign p_addr_cast_fu_286_p1 = tmp_1_fu_278_p3;
assign r3_fu_244_p2 = (ap_const_lv4_1 + r_i_phi_fu_149_p4);
assign r_i_mid2_fu_250_p3 = ((exitcond_i5_fu_230_p2[0:0]===1'b1)? r3_fu_244_p2: r_i_phi_fu_149_p4);
assign tmp_1_fu_278_p3 = {{r_i_mid2_fu_250_p3}, {ap_const_lv3_0}};
assign tmp_2_fu_296_p1 = p_addr2_fu_290_p2;
assign tmp_3_i_fu_313_p1 = tmp_9_i_reg_336;
assign tmp_8_i_trn_cast_fu_274_p1 = c_i_mid2_fu_236_p3;
assign tmp_9_i_fu_301_p2 = (c_i_cast2_fu_270_p1 + tmp_i_fu_262_p3);
assign tmp_fu_258_p1 = r_i_mid2_fu_250_p3[2:0];
assign tmp_i_fu_262_p3 = {{tmp_fu_258_p1}, {ap_const_lv3_0}};


endmodule //dct

