// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "array_io.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic array_io::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic array_io::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> array_io::ap_ST_st1_fsm_0 = "1";
const sc_lv<12> array_io::ap_ST_st2_fsm_1 = "10";
const sc_lv<12> array_io::ap_ST_st3_fsm_2 = "100";
const sc_lv<12> array_io::ap_ST_st4_fsm_3 = "1000";
const sc_lv<12> array_io::ap_ST_st5_fsm_4 = "10000";
const sc_lv<12> array_io::ap_ST_st6_fsm_5 = "100000";
const sc_lv<12> array_io::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<12> array_io::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<12> array_io::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<12> array_io::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<12> array_io::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<12> array_io::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<32> array_io::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> array_io::ap_const_lv1_1 = "1";
const sc_lv<32> array_io::ap_const_lv32_1 = "1";
const sc_lv<32> array_io::ap_const_lv32_2 = "10";
const sc_lv<32> array_io::ap_const_lv32_3 = "11";
const sc_lv<32> array_io::ap_const_lv32_4 = "100";
const sc_lv<32> array_io::ap_const_lv32_5 = "101";
const sc_lv<32> array_io::ap_const_lv32_6 = "110";
const sc_lv<32> array_io::ap_const_lv32_7 = "111";
const sc_lv<32> array_io::ap_const_lv32_8 = "1000";
const sc_lv<32> array_io::ap_const_lv32_9 = "1001";
const sc_lv<32> array_io::ap_const_lv32_A = "1010";
const sc_lv<64> array_io::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> array_io::ap_const_lv64_1 = "1";
const sc_lv<64> array_io::ap_const_lv64_8 = "1000";
const sc_lv<64> array_io::ap_const_lv64_2 = "10";
const sc_lv<64> array_io::ap_const_lv64_9 = "1001";
const sc_lv<64> array_io::ap_const_lv64_3 = "11";
const sc_lv<64> array_io::ap_const_lv64_A = "1010";
const sc_lv<64> array_io::ap_const_lv64_4 = "100";
const sc_lv<64> array_io::ap_const_lv64_B = "1011";
const sc_lv<64> array_io::ap_const_lv64_5 = "101";
const sc_lv<64> array_io::ap_const_lv64_C = "1100";
const sc_lv<64> array_io::ap_const_lv64_6 = "110";
const sc_lv<64> array_io::ap_const_lv64_D = "1101";
const sc_lv<64> array_io::ap_const_lv64_7 = "111";
const sc_lv<64> array_io::ap_const_lv64_E = "1110";
const sc_lv<64> array_io::ap_const_lv64_F = "1111";
const sc_lv<32> array_io::ap_const_lv32_B = "1011";

array_io::array_io(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_0_loc_assign_1_fu_468_p2);
    sensitive << ( acc_0_loc_assign_2_reg_968 );
    sensitive << ( tmp_2_8_fu_464_p1 );

    SC_METHOD(thread_acc_0_loc_assign_2_fu_436_p2);
    sensitive << ( acc_0 );
    sensitive << ( tmp_2_fu_432_p1 );

    SC_METHOD(thread_acc_0_loc_fu_481_p2);
    sensitive << ( acc_0_loc_assign_1_fu_468_p2 );
    sensitive << ( tmp_2_15_fu_477_p1 );

    SC_METHOD(thread_acc_1_loc_assign_1_fu_513_p2);
    sensitive << ( acc_1_loc_assign_2_reg_998 );
    sensitive << ( tmp_2_9_fu_509_p1 );

    SC_METHOD(thread_acc_1_loc_assign_2_fu_454_p2);
    sensitive << ( acc_1 );
    sensitive << ( tmp_2_1_fu_450_p1 );

    SC_METHOD(thread_acc_1_loc_fu_526_p2);
    sensitive << ( acc_1_loc_assign_1_fu_513_p2 );
    sensitive << ( tmp_2_16_fu_522_p1 );

    SC_METHOD(thread_acc_2_loc_assign_1_fu_578_p2);
    sensitive << ( acc_2_loc_assign_2_reg_1043 );
    sensitive << ( tmp_2_s_fu_574_p1 );

    SC_METHOD(thread_acc_2_loc_assign_2_fu_499_p2);
    sensitive << ( acc_2 );
    sensitive << ( tmp_2_2_fu_495_p1 );

    SC_METHOD(thread_acc_2_loc_fu_591_p2);
    sensitive << ( acc_2_loc_assign_1_fu_578_p2 );
    sensitive << ( tmp_2_17_fu_587_p1 );

    SC_METHOD(thread_acc_3_loc_assign_1_fu_643_p2);
    sensitive << ( acc_3_loc_assign_2_reg_1088 );
    sensitive << ( tmp_2_10_fu_639_p1 );

    SC_METHOD(thread_acc_3_loc_assign_2_fu_564_p2);
    sensitive << ( acc_3 );
    sensitive << ( tmp_2_3_fu_560_p1 );

    SC_METHOD(thread_acc_3_loc_fu_656_p2);
    sensitive << ( acc_3_loc_assign_1_fu_643_p2 );
    sensitive << ( tmp_2_18_fu_652_p1 );

    SC_METHOD(thread_acc_4_loc_assign_1_fu_708_p2);
    sensitive << ( acc_4_loc_assign_2_reg_1133 );
    sensitive << ( tmp_2_11_fu_704_p1 );

    SC_METHOD(thread_acc_4_loc_assign_2_fu_629_p2);
    sensitive << ( acc_4 );
    sensitive << ( tmp_2_4_fu_625_p1 );

    SC_METHOD(thread_acc_4_loc_fu_721_p2);
    sensitive << ( acc_4_loc_assign_1_fu_708_p2 );
    sensitive << ( tmp_2_19_fu_717_p1 );

    SC_METHOD(thread_acc_5_loc_assign_1_fu_773_p2);
    sensitive << ( acc_5_loc_assign_2_reg_1178 );
    sensitive << ( tmp_2_12_fu_769_p1 );

    SC_METHOD(thread_acc_5_loc_assign_2_fu_694_p2);
    sensitive << ( acc_5 );
    sensitive << ( tmp_2_5_fu_690_p1 );

    SC_METHOD(thread_acc_5_loc_fu_786_p2);
    sensitive << ( acc_5_loc_assign_1_fu_773_p2 );
    sensitive << ( tmp_2_20_fu_782_p1 );

    SC_METHOD(thread_acc_6_loc_assign_1_fu_838_p2);
    sensitive << ( acc_6_loc_assign_2_reg_1223 );
    sensitive << ( tmp_2_13_fu_834_p1 );

    SC_METHOD(thread_acc_6_loc_assign_2_fu_759_p2);
    sensitive << ( acc_6 );
    sensitive << ( tmp_2_6_fu_755_p1 );

    SC_METHOD(thread_acc_6_loc_fu_851_p2);
    sensitive << ( acc_6_loc_assign_1_fu_838_p2 );
    sensitive << ( tmp_2_21_fu_847_p1 );

    SC_METHOD(thread_acc_7_loc_assign_1_fu_885_p2);
    sensitive << ( acc_7_loc_assign_2_reg_1263 );
    sensitive << ( tmp_2_14_fu_881_p1 );

    SC_METHOD(thread_acc_7_loc_assign_2_fu_824_p2);
    sensitive << ( acc_7 );
    sensitive << ( tmp_2_7_fu_820_p1 );

    SC_METHOD(thread_acc_7_loc_fu_898_p2);
    sensitive << ( acc_7_loc_assign_1_fu_885_p2 );
    sensitive << ( tmp_2_22_fu_894_p1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_ap_sig_bdd_106);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_115);
    sensitive << ( d_o_0_full_n );
    sensitive << ( d_o_1_full_n );
    sensitive << ( d_o_2_full_n );
    sensitive << ( d_o_3_full_n );

    SC_METHOD(thread_ap_sig_bdd_124);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_133);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_142);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_151);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_160);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_178);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_364);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_90);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_98);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_bdd_160 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_bdd_178 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_bdd_364 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_28 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_bdd_90 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_bdd_98 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_bdd_106 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_bdd_124 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_bdd_133 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_bdd_142 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_bdd_151 );

    SC_METHOD(thread_d_i_0_address0);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_d_i_0_address1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_d_i_0_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_d_i_0_ce1);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_d_i_1_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_d_i_1_address1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_d_i_1_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_d_i_1_ce1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_d_o_0_din);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_reg_973 );
    sensitive << ( tmp_1_reg_1003 );
    sensitive << ( tmp_3_reg_1048 );
    sensitive << ( tmp_4_reg_1093 );
    sensitive << ( tmp_5_reg_1138 );
    sensitive << ( tmp_6_reg_1183 );
    sensitive << ( tmp_7_reg_1228 );
    sensitive << ( tmp_8_reg_1268 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_0_write);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_1_din);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_9_reg_1013 );
    sensitive << ( tmp_10_reg_1058 );
    sensitive << ( tmp_11_reg_1103 );
    sensitive << ( tmp_12_reg_1148 );
    sensitive << ( tmp_13_reg_1193 );
    sensitive << ( tmp_14_reg_1233 );
    sensitive << ( tmp_15_reg_1273 );
    sensitive << ( tmp_16_reg_1293 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_1_write);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_2_din);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( tmp_17_reg_1028 );
    sensitive << ( tmp_18_reg_1073 );
    sensitive << ( tmp_19_reg_1118 );
    sensitive << ( tmp_20_reg_1163 );
    sensitive << ( tmp_21_reg_1208 );
    sensitive << ( tmp_22_reg_1248 );
    sensitive << ( tmp_23_reg_1283 );
    sensitive << ( tmp_24_reg_1303 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_2_write);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_d_o_3_din);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( tmp_25_fu_551_p1 );
    sensitive << ( tmp_26_fu_616_p1 );
    sensitive << ( tmp_27_fu_681_p1 );
    sensitive << ( tmp_28_fu_746_p1 );
    sensitive << ( tmp_29_fu_811_p1 );
    sensitive << ( tmp_30_fu_876_p1 );
    sensitive << ( tmp_31_fu_923_p1 );
    sensitive << ( tmp_32_fu_943_p1 );

    SC_METHOD(thread_d_o_3_write);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_bdd_115 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_temp_1_fu_605_p2);
    sensitive << ( acc_1_loc_reg_1068 );
    sensitive << ( tmp_2_24_fu_601_p1 );

    SC_METHOD(thread_temp_2_fu_670_p2);
    sensitive << ( acc_2_loc_reg_1113 );
    sensitive << ( tmp_2_25_fu_666_p1 );

    SC_METHOD(thread_temp_3_fu_735_p2);
    sensitive << ( acc_3_loc_reg_1158 );
    sensitive << ( tmp_2_26_fu_731_p1 );

    SC_METHOD(thread_temp_4_fu_800_p2);
    sensitive << ( acc_4_loc_reg_1203 );
    sensitive << ( tmp_2_27_fu_796_p1 );

    SC_METHOD(thread_temp_5_fu_865_p2);
    sensitive << ( acc_5_loc_reg_1243 );
    sensitive << ( tmp_2_28_fu_861_p1 );

    SC_METHOD(thread_temp_6_fu_912_p2);
    sensitive << ( acc_6_loc_reg_1278 );
    sensitive << ( tmp_2_29_fu_908_p1 );

    SC_METHOD(thread_temp_7_fu_932_p2);
    sensitive << ( acc_7_loc_reg_1298 );
    sensitive << ( tmp_2_30_fu_928_p1 );

    SC_METHOD(thread_temp_s_fu_540_p2);
    sensitive << ( acc_0_loc_reg_1023 );
    sensitive << ( tmp_2_23_fu_536_p1 );

    SC_METHOD(thread_tmp_10_fu_518_p1);
    sensitive << ( acc_1_loc_assign_1_fu_513_p2 );

    SC_METHOD(thread_tmp_11_fu_583_p1);
    sensitive << ( acc_2_loc_assign_1_fu_578_p2 );

    SC_METHOD(thread_tmp_12_fu_648_p1);
    sensitive << ( acc_3_loc_assign_1_fu_643_p2 );

    SC_METHOD(thread_tmp_13_fu_713_p1);
    sensitive << ( acc_4_loc_assign_1_fu_708_p2 );

    SC_METHOD(thread_tmp_14_fu_778_p1);
    sensitive << ( acc_5_loc_assign_1_fu_773_p2 );

    SC_METHOD(thread_tmp_15_fu_843_p1);
    sensitive << ( acc_6_loc_assign_1_fu_838_p2 );

    SC_METHOD(thread_tmp_16_fu_890_p1);
    sensitive << ( acc_7_loc_assign_1_fu_885_p2 );

    SC_METHOD(thread_tmp_17_fu_487_p1);
    sensitive << ( acc_0_loc_fu_481_p2 );

    SC_METHOD(thread_tmp_18_fu_532_p1);
    sensitive << ( acc_1_loc_fu_526_p2 );

    SC_METHOD(thread_tmp_19_fu_597_p1);
    sensitive << ( acc_2_loc_fu_591_p2 );

    SC_METHOD(thread_tmp_1_fu_460_p1);
    sensitive << ( acc_1_loc_assign_2_fu_454_p2 );

    SC_METHOD(thread_tmp_20_fu_662_p1);
    sensitive << ( acc_3_loc_fu_656_p2 );

    SC_METHOD(thread_tmp_21_fu_727_p1);
    sensitive << ( acc_4_loc_fu_721_p2 );

    SC_METHOD(thread_tmp_22_fu_792_p1);
    sensitive << ( acc_5_loc_fu_786_p2 );

    SC_METHOD(thread_tmp_23_fu_857_p1);
    sensitive << ( acc_6_loc_fu_851_p2 );

    SC_METHOD(thread_tmp_24_fu_904_p1);
    sensitive << ( acc_7_loc_fu_898_p2 );

    SC_METHOD(thread_tmp_25_fu_551_p1);
    sensitive << ( temp_s_fu_540_p2 );

    SC_METHOD(thread_tmp_26_fu_616_p1);
    sensitive << ( temp_1_fu_605_p2 );

    SC_METHOD(thread_tmp_27_fu_681_p1);
    sensitive << ( temp_2_fu_670_p2 );

    SC_METHOD(thread_tmp_28_fu_746_p1);
    sensitive << ( temp_3_fu_735_p2 );

    SC_METHOD(thread_tmp_29_fu_811_p1);
    sensitive << ( temp_4_fu_800_p2 );

    SC_METHOD(thread_tmp_2_10_fu_639_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_11_fu_704_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_12_fu_769_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_13_fu_834_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_14_fu_881_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_15_fu_477_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_16_fu_522_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_17_fu_587_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_18_fu_652_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_19_fu_717_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_1_fu_450_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_20_fu_782_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_21_fu_847_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_22_fu_894_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_23_fu_536_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_24_fu_601_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_25_fu_666_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_26_fu_731_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_27_fu_796_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_28_fu_861_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_29_fu_908_p1);
    sensitive << ( reg_424 );

    SC_METHOD(thread_tmp_2_2_fu_495_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_30_fu_928_p1);
    sensitive << ( reg_420 );

    SC_METHOD(thread_tmp_2_3_fu_560_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_4_fu_625_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_5_fu_690_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_6_fu_755_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_7_fu_820_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_8_fu_464_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_9_fu_509_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_2_fu_432_p1);
    sensitive << ( reg_412 );

    SC_METHOD(thread_tmp_2_s_fu_574_p1);
    sensitive << ( reg_416 );

    SC_METHOD(thread_tmp_30_fu_876_p1);
    sensitive << ( temp_5_fu_865_p2 );

    SC_METHOD(thread_tmp_31_fu_923_p1);
    sensitive << ( temp_6_fu_912_p2 );

    SC_METHOD(thread_tmp_32_fu_943_p1);
    sensitive << ( temp_7_fu_932_p2 );

    SC_METHOD(thread_tmp_3_fu_505_p1);
    sensitive << ( acc_2_loc_assign_2_fu_499_p2 );

    SC_METHOD(thread_tmp_4_fu_570_p1);
    sensitive << ( acc_3_loc_assign_2_fu_564_p2 );

    SC_METHOD(thread_tmp_5_fu_635_p1);
    sensitive << ( acc_4_loc_assign_2_fu_629_p2 );

    SC_METHOD(thread_tmp_6_fu_700_p1);
    sensitive << ( acc_5_loc_assign_2_fu_694_p2 );

    SC_METHOD(thread_tmp_7_fu_765_p1);
    sensitive << ( acc_6_loc_assign_2_fu_759_p2 );

    SC_METHOD(thread_tmp_8_fu_830_p1);
    sensitive << ( acc_7_loc_assign_2_fu_824_p2 );

    SC_METHOD(thread_tmp_9_fu_473_p1);
    sensitive << ( acc_0_loc_assign_1_fu_468_p2 );

    SC_METHOD(thread_tmp_fu_442_p1);
    sensitive << ( acc_0_loc_assign_2_fu_436_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_115 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "000000000001";
    acc_0 = "00000000000000000000000000000000";
    acc_1 = "00000000000000000000000000000000";
    acc_2 = "00000000000000000000000000000000";
    acc_3 = "00000000000000000000000000000000";
    acc_4 = "00000000000000000000000000000000";
    acc_5 = "00000000000000000000000000000000";
    acc_6 = "00000000000000000000000000000000";
    acc_7 = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "array_io_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, d_o_0_din, "(port)d_o_0_din");
    sc_trace(mVcdFile, d_o_0_full_n, "(port)d_o_0_full_n");
    sc_trace(mVcdFile, d_o_0_write, "(port)d_o_0_write");
    sc_trace(mVcdFile, d_o_1_din, "(port)d_o_1_din");
    sc_trace(mVcdFile, d_o_1_full_n, "(port)d_o_1_full_n");
    sc_trace(mVcdFile, d_o_1_write, "(port)d_o_1_write");
    sc_trace(mVcdFile, d_o_2_din, "(port)d_o_2_din");
    sc_trace(mVcdFile, d_o_2_full_n, "(port)d_o_2_full_n");
    sc_trace(mVcdFile, d_o_2_write, "(port)d_o_2_write");
    sc_trace(mVcdFile, d_o_3_din, "(port)d_o_3_din");
    sc_trace(mVcdFile, d_o_3_full_n, "(port)d_o_3_full_n");
    sc_trace(mVcdFile, d_o_3_write, "(port)d_o_3_write");
    sc_trace(mVcdFile, d_i_0_address0, "(port)d_i_0_address0");
    sc_trace(mVcdFile, d_i_0_ce0, "(port)d_i_0_ce0");
    sc_trace(mVcdFile, d_i_0_q0, "(port)d_i_0_q0");
    sc_trace(mVcdFile, d_i_0_address1, "(port)d_i_0_address1");
    sc_trace(mVcdFile, d_i_0_ce1, "(port)d_i_0_ce1");
    sc_trace(mVcdFile, d_i_0_q1, "(port)d_i_0_q1");
    sc_trace(mVcdFile, d_i_1_address0, "(port)d_i_1_address0");
    sc_trace(mVcdFile, d_i_1_ce0, "(port)d_i_1_ce0");
    sc_trace(mVcdFile, d_i_1_q0, "(port)d_i_1_q0");
    sc_trace(mVcdFile, d_i_1_address1, "(port)d_i_1_address1");
    sc_trace(mVcdFile, d_i_1_ce1, "(port)d_i_1_ce1");
    sc_trace(mVcdFile, d_i_1_q1, "(port)d_i_1_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_28, "ap_sig_bdd_28");
    sc_trace(mVcdFile, acc_0, "acc_0");
    sc_trace(mVcdFile, acc_1, "acc_1");
    sc_trace(mVcdFile, acc_2, "acc_2");
    sc_trace(mVcdFile, acc_3, "acc_3");
    sc_trace(mVcdFile, acc_4, "acc_4");
    sc_trace(mVcdFile, acc_5, "acc_5");
    sc_trace(mVcdFile, acc_6, "acc_6");
    sc_trace(mVcdFile, acc_7, "acc_7");
    sc_trace(mVcdFile, reg_412, "reg_412");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_83, "ap_sig_bdd_83");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_bdd_90, "ap_sig_bdd_90");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_bdd_98, "ap_sig_bdd_98");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_bdd_106, "ap_sig_bdd_106");
    sc_trace(mVcdFile, ap_sig_bdd_115, "ap_sig_bdd_115");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_bdd_124, "ap_sig_bdd_124");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_bdd_133, "ap_sig_bdd_133");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_bdd_142, "ap_sig_bdd_142");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_bdd_151, "ap_sig_bdd_151");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_bdd_160, "ap_sig_bdd_160");
    sc_trace(mVcdFile, reg_416, "reg_416");
    sc_trace(mVcdFile, reg_420, "reg_420");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_bdd_178, "ap_sig_bdd_178");
    sc_trace(mVcdFile, reg_424, "reg_424");
    sc_trace(mVcdFile, acc_0_loc_assign_2_fu_436_p2, "acc_0_loc_assign_2_fu_436_p2");
    sc_trace(mVcdFile, acc_0_loc_assign_2_reg_968, "acc_0_loc_assign_2_reg_968");
    sc_trace(mVcdFile, tmp_fu_442_p1, "tmp_fu_442_p1");
    sc_trace(mVcdFile, tmp_reg_973, "tmp_reg_973");
    sc_trace(mVcdFile, acc_1_loc_assign_2_fu_454_p2, "acc_1_loc_assign_2_fu_454_p2");
    sc_trace(mVcdFile, acc_1_loc_assign_2_reg_998, "acc_1_loc_assign_2_reg_998");
    sc_trace(mVcdFile, tmp_1_fu_460_p1, "tmp_1_fu_460_p1");
    sc_trace(mVcdFile, tmp_1_reg_1003, "tmp_1_reg_1003");
    sc_trace(mVcdFile, tmp_9_fu_473_p1, "tmp_9_fu_473_p1");
    sc_trace(mVcdFile, tmp_9_reg_1013, "tmp_9_reg_1013");
    sc_trace(mVcdFile, acc_0_loc_fu_481_p2, "acc_0_loc_fu_481_p2");
    sc_trace(mVcdFile, acc_0_loc_reg_1023, "acc_0_loc_reg_1023");
    sc_trace(mVcdFile, tmp_17_fu_487_p1, "tmp_17_fu_487_p1");
    sc_trace(mVcdFile, tmp_17_reg_1028, "tmp_17_reg_1028");
    sc_trace(mVcdFile, acc_2_loc_assign_2_fu_499_p2, "acc_2_loc_assign_2_fu_499_p2");
    sc_trace(mVcdFile, acc_2_loc_assign_2_reg_1043, "acc_2_loc_assign_2_reg_1043");
    sc_trace(mVcdFile, tmp_3_fu_505_p1, "tmp_3_fu_505_p1");
    sc_trace(mVcdFile, tmp_3_reg_1048, "tmp_3_reg_1048");
    sc_trace(mVcdFile, tmp_10_fu_518_p1, "tmp_10_fu_518_p1");
    sc_trace(mVcdFile, tmp_10_reg_1058, "tmp_10_reg_1058");
    sc_trace(mVcdFile, acc_1_loc_fu_526_p2, "acc_1_loc_fu_526_p2");
    sc_trace(mVcdFile, acc_1_loc_reg_1068, "acc_1_loc_reg_1068");
    sc_trace(mVcdFile, tmp_18_fu_532_p1, "tmp_18_fu_532_p1");
    sc_trace(mVcdFile, tmp_18_reg_1073, "tmp_18_reg_1073");
    sc_trace(mVcdFile, acc_3_loc_assign_2_fu_564_p2, "acc_3_loc_assign_2_fu_564_p2");
    sc_trace(mVcdFile, acc_3_loc_assign_2_reg_1088, "acc_3_loc_assign_2_reg_1088");
    sc_trace(mVcdFile, tmp_4_fu_570_p1, "tmp_4_fu_570_p1");
    sc_trace(mVcdFile, tmp_4_reg_1093, "tmp_4_reg_1093");
    sc_trace(mVcdFile, tmp_11_fu_583_p1, "tmp_11_fu_583_p1");
    sc_trace(mVcdFile, tmp_11_reg_1103, "tmp_11_reg_1103");
    sc_trace(mVcdFile, acc_2_loc_fu_591_p2, "acc_2_loc_fu_591_p2");
    sc_trace(mVcdFile, acc_2_loc_reg_1113, "acc_2_loc_reg_1113");
    sc_trace(mVcdFile, tmp_19_fu_597_p1, "tmp_19_fu_597_p1");
    sc_trace(mVcdFile, tmp_19_reg_1118, "tmp_19_reg_1118");
    sc_trace(mVcdFile, acc_4_loc_assign_2_fu_629_p2, "acc_4_loc_assign_2_fu_629_p2");
    sc_trace(mVcdFile, acc_4_loc_assign_2_reg_1133, "acc_4_loc_assign_2_reg_1133");
    sc_trace(mVcdFile, tmp_5_fu_635_p1, "tmp_5_fu_635_p1");
    sc_trace(mVcdFile, tmp_5_reg_1138, "tmp_5_reg_1138");
    sc_trace(mVcdFile, tmp_12_fu_648_p1, "tmp_12_fu_648_p1");
    sc_trace(mVcdFile, tmp_12_reg_1148, "tmp_12_reg_1148");
    sc_trace(mVcdFile, acc_3_loc_fu_656_p2, "acc_3_loc_fu_656_p2");
    sc_trace(mVcdFile, acc_3_loc_reg_1158, "acc_3_loc_reg_1158");
    sc_trace(mVcdFile, tmp_20_fu_662_p1, "tmp_20_fu_662_p1");
    sc_trace(mVcdFile, tmp_20_reg_1163, "tmp_20_reg_1163");
    sc_trace(mVcdFile, acc_5_loc_assign_2_fu_694_p2, "acc_5_loc_assign_2_fu_694_p2");
    sc_trace(mVcdFile, acc_5_loc_assign_2_reg_1178, "acc_5_loc_assign_2_reg_1178");
    sc_trace(mVcdFile, tmp_6_fu_700_p1, "tmp_6_fu_700_p1");
    sc_trace(mVcdFile, tmp_6_reg_1183, "tmp_6_reg_1183");
    sc_trace(mVcdFile, tmp_13_fu_713_p1, "tmp_13_fu_713_p1");
    sc_trace(mVcdFile, tmp_13_reg_1193, "tmp_13_reg_1193");
    sc_trace(mVcdFile, acc_4_loc_fu_721_p2, "acc_4_loc_fu_721_p2");
    sc_trace(mVcdFile, acc_4_loc_reg_1203, "acc_4_loc_reg_1203");
    sc_trace(mVcdFile, tmp_21_fu_727_p1, "tmp_21_fu_727_p1");
    sc_trace(mVcdFile, tmp_21_reg_1208, "tmp_21_reg_1208");
    sc_trace(mVcdFile, acc_6_loc_assign_2_fu_759_p2, "acc_6_loc_assign_2_fu_759_p2");
    sc_trace(mVcdFile, acc_6_loc_assign_2_reg_1223, "acc_6_loc_assign_2_reg_1223");
    sc_trace(mVcdFile, tmp_7_fu_765_p1, "tmp_7_fu_765_p1");
    sc_trace(mVcdFile, tmp_7_reg_1228, "tmp_7_reg_1228");
    sc_trace(mVcdFile, tmp_14_fu_778_p1, "tmp_14_fu_778_p1");
    sc_trace(mVcdFile, tmp_14_reg_1233, "tmp_14_reg_1233");
    sc_trace(mVcdFile, acc_5_loc_fu_786_p2, "acc_5_loc_fu_786_p2");
    sc_trace(mVcdFile, acc_5_loc_reg_1243, "acc_5_loc_reg_1243");
    sc_trace(mVcdFile, tmp_22_fu_792_p1, "tmp_22_fu_792_p1");
    sc_trace(mVcdFile, tmp_22_reg_1248, "tmp_22_reg_1248");
    sc_trace(mVcdFile, acc_7_loc_assign_2_fu_824_p2, "acc_7_loc_assign_2_fu_824_p2");
    sc_trace(mVcdFile, acc_7_loc_assign_2_reg_1263, "acc_7_loc_assign_2_reg_1263");
    sc_trace(mVcdFile, tmp_8_fu_830_p1, "tmp_8_fu_830_p1");
    sc_trace(mVcdFile, tmp_8_reg_1268, "tmp_8_reg_1268");
    sc_trace(mVcdFile, tmp_15_fu_843_p1, "tmp_15_fu_843_p1");
    sc_trace(mVcdFile, tmp_15_reg_1273, "tmp_15_reg_1273");
    sc_trace(mVcdFile, acc_6_loc_fu_851_p2, "acc_6_loc_fu_851_p2");
    sc_trace(mVcdFile, acc_6_loc_reg_1278, "acc_6_loc_reg_1278");
    sc_trace(mVcdFile, tmp_23_fu_857_p1, "tmp_23_fu_857_p1");
    sc_trace(mVcdFile, tmp_23_reg_1283, "tmp_23_reg_1283");
    sc_trace(mVcdFile, tmp_16_fu_890_p1, "tmp_16_fu_890_p1");
    sc_trace(mVcdFile, tmp_16_reg_1293, "tmp_16_reg_1293");
    sc_trace(mVcdFile, acc_7_loc_fu_898_p2, "acc_7_loc_fu_898_p2");
    sc_trace(mVcdFile, acc_7_loc_reg_1298, "acc_7_loc_reg_1298");
    sc_trace(mVcdFile, tmp_24_fu_904_p1, "tmp_24_fu_904_p1");
    sc_trace(mVcdFile, tmp_24_reg_1303, "tmp_24_reg_1303");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_bdd_364, "ap_sig_bdd_364");
    sc_trace(mVcdFile, tmp_25_fu_551_p1, "tmp_25_fu_551_p1");
    sc_trace(mVcdFile, tmp_26_fu_616_p1, "tmp_26_fu_616_p1");
    sc_trace(mVcdFile, tmp_27_fu_681_p1, "tmp_27_fu_681_p1");
    sc_trace(mVcdFile, tmp_28_fu_746_p1, "tmp_28_fu_746_p1");
    sc_trace(mVcdFile, tmp_29_fu_811_p1, "tmp_29_fu_811_p1");
    sc_trace(mVcdFile, tmp_30_fu_876_p1, "tmp_30_fu_876_p1");
    sc_trace(mVcdFile, tmp_31_fu_923_p1, "tmp_31_fu_923_p1");
    sc_trace(mVcdFile, tmp_32_fu_943_p1, "tmp_32_fu_943_p1");
    sc_trace(mVcdFile, temp_s_fu_540_p2, "temp_s_fu_540_p2");
    sc_trace(mVcdFile, temp_1_fu_605_p2, "temp_1_fu_605_p2");
    sc_trace(mVcdFile, temp_2_fu_670_p2, "temp_2_fu_670_p2");
    sc_trace(mVcdFile, temp_3_fu_735_p2, "temp_3_fu_735_p2");
    sc_trace(mVcdFile, temp_4_fu_800_p2, "temp_4_fu_800_p2");
    sc_trace(mVcdFile, temp_5_fu_865_p2, "temp_5_fu_865_p2");
    sc_trace(mVcdFile, temp_6_fu_912_p2, "temp_6_fu_912_p2");
    sc_trace(mVcdFile, temp_7_fu_932_p2, "temp_7_fu_932_p2");
    sc_trace(mVcdFile, tmp_2_fu_432_p1, "tmp_2_fu_432_p1");
    sc_trace(mVcdFile, tmp_2_1_fu_450_p1, "tmp_2_1_fu_450_p1");
    sc_trace(mVcdFile, tmp_2_8_fu_464_p1, "tmp_2_8_fu_464_p1");
    sc_trace(mVcdFile, acc_0_loc_assign_1_fu_468_p2, "acc_0_loc_assign_1_fu_468_p2");
    sc_trace(mVcdFile, tmp_2_15_fu_477_p1, "tmp_2_15_fu_477_p1");
    sc_trace(mVcdFile, tmp_2_2_fu_495_p1, "tmp_2_2_fu_495_p1");
    sc_trace(mVcdFile, tmp_2_9_fu_509_p1, "tmp_2_9_fu_509_p1");
    sc_trace(mVcdFile, acc_1_loc_assign_1_fu_513_p2, "acc_1_loc_assign_1_fu_513_p2");
    sc_trace(mVcdFile, tmp_2_16_fu_522_p1, "tmp_2_16_fu_522_p1");
    sc_trace(mVcdFile, tmp_2_23_fu_536_p1, "tmp_2_23_fu_536_p1");
    sc_trace(mVcdFile, tmp_2_3_fu_560_p1, "tmp_2_3_fu_560_p1");
    sc_trace(mVcdFile, tmp_2_s_fu_574_p1, "tmp_2_s_fu_574_p1");
    sc_trace(mVcdFile, acc_2_loc_assign_1_fu_578_p2, "acc_2_loc_assign_1_fu_578_p2");
    sc_trace(mVcdFile, tmp_2_17_fu_587_p1, "tmp_2_17_fu_587_p1");
    sc_trace(mVcdFile, tmp_2_24_fu_601_p1, "tmp_2_24_fu_601_p1");
    sc_trace(mVcdFile, tmp_2_4_fu_625_p1, "tmp_2_4_fu_625_p1");
    sc_trace(mVcdFile, tmp_2_10_fu_639_p1, "tmp_2_10_fu_639_p1");
    sc_trace(mVcdFile, acc_3_loc_assign_1_fu_643_p2, "acc_3_loc_assign_1_fu_643_p2");
    sc_trace(mVcdFile, tmp_2_18_fu_652_p1, "tmp_2_18_fu_652_p1");
    sc_trace(mVcdFile, tmp_2_25_fu_666_p1, "tmp_2_25_fu_666_p1");
    sc_trace(mVcdFile, tmp_2_5_fu_690_p1, "tmp_2_5_fu_690_p1");
    sc_trace(mVcdFile, tmp_2_11_fu_704_p1, "tmp_2_11_fu_704_p1");
    sc_trace(mVcdFile, acc_4_loc_assign_1_fu_708_p2, "acc_4_loc_assign_1_fu_708_p2");
    sc_trace(mVcdFile, tmp_2_19_fu_717_p1, "tmp_2_19_fu_717_p1");
    sc_trace(mVcdFile, tmp_2_26_fu_731_p1, "tmp_2_26_fu_731_p1");
    sc_trace(mVcdFile, tmp_2_6_fu_755_p1, "tmp_2_6_fu_755_p1");
    sc_trace(mVcdFile, tmp_2_12_fu_769_p1, "tmp_2_12_fu_769_p1");
    sc_trace(mVcdFile, acc_5_loc_assign_1_fu_773_p2, "acc_5_loc_assign_1_fu_773_p2");
    sc_trace(mVcdFile, tmp_2_20_fu_782_p1, "tmp_2_20_fu_782_p1");
    sc_trace(mVcdFile, tmp_2_27_fu_796_p1, "tmp_2_27_fu_796_p1");
    sc_trace(mVcdFile, tmp_2_7_fu_820_p1, "tmp_2_7_fu_820_p1");
    sc_trace(mVcdFile, tmp_2_13_fu_834_p1, "tmp_2_13_fu_834_p1");
    sc_trace(mVcdFile, acc_6_loc_assign_1_fu_838_p2, "acc_6_loc_assign_1_fu_838_p2");
    sc_trace(mVcdFile, tmp_2_21_fu_847_p1, "tmp_2_21_fu_847_p1");
    sc_trace(mVcdFile, tmp_2_28_fu_861_p1, "tmp_2_28_fu_861_p1");
    sc_trace(mVcdFile, tmp_2_14_fu_881_p1, "tmp_2_14_fu_881_p1");
    sc_trace(mVcdFile, acc_7_loc_assign_1_fu_885_p2, "acc_7_loc_assign_1_fu_885_p2");
    sc_trace(mVcdFile, tmp_2_22_fu_894_p1, "tmp_2_22_fu_894_p1");
    sc_trace(mVcdFile, tmp_2_29_fu_908_p1, "tmp_2_29_fu_908_p1");
    sc_trace(mVcdFile, tmp_2_30_fu_928_p1, "tmp_2_30_fu_928_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("array_io.hdltvin.dat");
    mHdltvoutHandle.open("array_io.hdltvout.dat");
}

array_io::~array_io() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void array_io::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && !ap_sig_bdd_115.read())) {
        acc_0 = temp_s_fu_540_p2.read();
        acc_1_loc_reg_1068 = acc_1_loc_fu_526_p2.read();
        acc_2_loc_assign_2_reg_1043 = acc_2_loc_assign_2_fu_499_p2.read();
        tmp_10_reg_1058 = tmp_10_fu_518_p1.read();
        tmp_18_reg_1073 = tmp_18_fu_532_p1.read();
        tmp_3_reg_1048 = tmp_3_fu_505_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        acc_0_loc_assign_2_reg_968 = acc_0_loc_assign_2_fu_436_p2.read();
        tmp_reg_973 = tmp_fu_442_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        acc_0_loc_reg_1023 = acc_0_loc_fu_481_p2.read();
        acc_1_loc_assign_2_reg_998 = acc_1_loc_assign_2_fu_454_p2.read();
        tmp_17_reg_1028 = tmp_17_fu_487_p1.read();
        tmp_1_reg_1003 = tmp_1_fu_460_p1.read();
        tmp_9_reg_1013 = tmp_9_fu_473_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()))) {
        acc_1 = temp_1_fu_605_p2.read();
        acc_2_loc_reg_1113 = acc_2_loc_fu_591_p2.read();
        acc_3_loc_assign_2_reg_1088 = acc_3_loc_assign_2_fu_564_p2.read();
        tmp_11_reg_1103 = tmp_11_fu_583_p1.read();
        tmp_19_reg_1118 = tmp_19_fu_597_p1.read();
        tmp_4_reg_1093 = tmp_4_fu_570_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        acc_2 = temp_2_fu_670_p2.read();
        acc_3_loc_reg_1158 = acc_3_loc_fu_656_p2.read();
        acc_4_loc_assign_2_reg_1133 = acc_4_loc_assign_2_fu_629_p2.read();
        tmp_12_reg_1148 = tmp_12_fu_648_p1.read();
        tmp_20_reg_1163 = tmp_20_fu_662_p1.read();
        tmp_5_reg_1138 = tmp_5_fu_635_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()))) {
        acc_3 = temp_3_fu_735_p2.read();
        acc_4_loc_reg_1203 = acc_4_loc_fu_721_p2.read();
        acc_5_loc_assign_2_reg_1178 = acc_5_loc_assign_2_fu_694_p2.read();
        tmp_13_reg_1193 = tmp_13_fu_713_p1.read();
        tmp_21_reg_1208 = tmp_21_fu_727_p1.read();
        tmp_6_reg_1183 = tmp_6_fu_700_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        acc_4 = temp_4_fu_800_p2.read();
        acc_5_loc_reg_1243 = acc_5_loc_fu_786_p2.read();
        acc_6_loc_assign_2_reg_1223 = acc_6_loc_assign_2_fu_759_p2.read();
        tmp_14_reg_1233 = tmp_14_fu_778_p1.read();
        tmp_22_reg_1248 = tmp_22_fu_792_p1.read();
        tmp_7_reg_1228 = tmp_7_fu_765_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()))) {
        acc_5 = temp_5_fu_865_p2.read();
        acc_6_loc_reg_1278 = acc_6_loc_fu_851_p2.read();
        acc_7_loc_assign_2_reg_1263 = acc_7_loc_assign_2_fu_824_p2.read();
        tmp_15_reg_1273 = tmp_15_fu_843_p1.read();
        tmp_23_reg_1283 = tmp_23_fu_857_p1.read();
        tmp_8_reg_1268 = tmp_8_fu_830_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()))) {
        acc_6 = temp_6_fu_912_p2.read();
        acc_7_loc_reg_1298 = acc_7_loc_fu_898_p2.read();
        tmp_16_reg_1293 = tmp_16_fu_890_p1.read();
        tmp_24_reg_1303 = tmp_24_fu_904_p1.read();
    }
    if ((!ap_sig_bdd_115.read() && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        acc_7 = temp_7_fu_932_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
  !ap_sig_bdd_115.read()) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())))) {
        reg_412 = d_i_0_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
  !ap_sig_bdd_115.read()) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())))) {
        reg_416 = d_i_0_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
  !ap_sig_bdd_115.read()) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())))) {
        reg_420 = d_i_1_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
  !ap_sig_bdd_115.read()) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || (!ap_sig_bdd_115.read() && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())))) {
        reg_424 = d_i_1_q1.read();
    }
}

void array_io::thread_acc_0_loc_assign_1_fu_468_p2() {
    acc_0_loc_assign_1_fu_468_p2 = (!acc_0_loc_assign_2_reg_968.read().is_01() || !tmp_2_8_fu_464_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_0_loc_assign_2_reg_968.read()) + sc_bigint<32>(tmp_2_8_fu_464_p1.read()));
}

void array_io::thread_acc_0_loc_assign_2_fu_436_p2() {
    acc_0_loc_assign_2_fu_436_p2 = (!acc_0.read().is_01() || !tmp_2_fu_432_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_0.read()) + sc_bigint<32>(tmp_2_fu_432_p1.read()));
}

void array_io::thread_acc_0_loc_fu_481_p2() {
    acc_0_loc_fu_481_p2 = (!acc_0_loc_assign_1_fu_468_p2.read().is_01() || !tmp_2_15_fu_477_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_0_loc_assign_1_fu_468_p2.read()) + sc_bigint<32>(tmp_2_15_fu_477_p1.read()));
}

void array_io::thread_acc_1_loc_assign_1_fu_513_p2() {
    acc_1_loc_assign_1_fu_513_p2 = (!acc_1_loc_assign_2_reg_998.read().is_01() || !tmp_2_9_fu_509_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_1_loc_assign_2_reg_998.read()) + sc_bigint<32>(tmp_2_9_fu_509_p1.read()));
}

void array_io::thread_acc_1_loc_assign_2_fu_454_p2() {
    acc_1_loc_assign_2_fu_454_p2 = (!acc_1.read().is_01() || !tmp_2_1_fu_450_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_1.read()) + sc_bigint<32>(tmp_2_1_fu_450_p1.read()));
}

void array_io::thread_acc_1_loc_fu_526_p2() {
    acc_1_loc_fu_526_p2 = (!acc_1_loc_assign_1_fu_513_p2.read().is_01() || !tmp_2_16_fu_522_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_1_loc_assign_1_fu_513_p2.read()) + sc_bigint<32>(tmp_2_16_fu_522_p1.read()));
}

void array_io::thread_acc_2_loc_assign_1_fu_578_p2() {
    acc_2_loc_assign_1_fu_578_p2 = (!acc_2_loc_assign_2_reg_1043.read().is_01() || !tmp_2_s_fu_574_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_2_loc_assign_2_reg_1043.read()) + sc_bigint<32>(tmp_2_s_fu_574_p1.read()));
}

void array_io::thread_acc_2_loc_assign_2_fu_499_p2() {
    acc_2_loc_assign_2_fu_499_p2 = (!acc_2.read().is_01() || !tmp_2_2_fu_495_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_2.read()) + sc_bigint<32>(tmp_2_2_fu_495_p1.read()));
}

void array_io::thread_acc_2_loc_fu_591_p2() {
    acc_2_loc_fu_591_p2 = (!acc_2_loc_assign_1_fu_578_p2.read().is_01() || !tmp_2_17_fu_587_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_2_loc_assign_1_fu_578_p2.read()) + sc_bigint<32>(tmp_2_17_fu_587_p1.read()));
}

void array_io::thread_acc_3_loc_assign_1_fu_643_p2() {
    acc_3_loc_assign_1_fu_643_p2 = (!acc_3_loc_assign_2_reg_1088.read().is_01() || !tmp_2_10_fu_639_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_3_loc_assign_2_reg_1088.read()) + sc_bigint<32>(tmp_2_10_fu_639_p1.read()));
}

void array_io::thread_acc_3_loc_assign_2_fu_564_p2() {
    acc_3_loc_assign_2_fu_564_p2 = (!acc_3.read().is_01() || !tmp_2_3_fu_560_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_3.read()) + sc_bigint<32>(tmp_2_3_fu_560_p1.read()));
}

void array_io::thread_acc_3_loc_fu_656_p2() {
    acc_3_loc_fu_656_p2 = (!acc_3_loc_assign_1_fu_643_p2.read().is_01() || !tmp_2_18_fu_652_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_3_loc_assign_1_fu_643_p2.read()) + sc_bigint<32>(tmp_2_18_fu_652_p1.read()));
}

void array_io::thread_acc_4_loc_assign_1_fu_708_p2() {
    acc_4_loc_assign_1_fu_708_p2 = (!acc_4_loc_assign_2_reg_1133.read().is_01() || !tmp_2_11_fu_704_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_4_loc_assign_2_reg_1133.read()) + sc_bigint<32>(tmp_2_11_fu_704_p1.read()));
}

void array_io::thread_acc_4_loc_assign_2_fu_629_p2() {
    acc_4_loc_assign_2_fu_629_p2 = (!acc_4.read().is_01() || !tmp_2_4_fu_625_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_4.read()) + sc_bigint<32>(tmp_2_4_fu_625_p1.read()));
}

void array_io::thread_acc_4_loc_fu_721_p2() {
    acc_4_loc_fu_721_p2 = (!acc_4_loc_assign_1_fu_708_p2.read().is_01() || !tmp_2_19_fu_717_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_4_loc_assign_1_fu_708_p2.read()) + sc_bigint<32>(tmp_2_19_fu_717_p1.read()));
}

void array_io::thread_acc_5_loc_assign_1_fu_773_p2() {
    acc_5_loc_assign_1_fu_773_p2 = (!acc_5_loc_assign_2_reg_1178.read().is_01() || !tmp_2_12_fu_769_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_5_loc_assign_2_reg_1178.read()) + sc_bigint<32>(tmp_2_12_fu_769_p1.read()));
}

void array_io::thread_acc_5_loc_assign_2_fu_694_p2() {
    acc_5_loc_assign_2_fu_694_p2 = (!acc_5.read().is_01() || !tmp_2_5_fu_690_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_5.read()) + sc_bigint<32>(tmp_2_5_fu_690_p1.read()));
}

void array_io::thread_acc_5_loc_fu_786_p2() {
    acc_5_loc_fu_786_p2 = (!acc_5_loc_assign_1_fu_773_p2.read().is_01() || !tmp_2_20_fu_782_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_5_loc_assign_1_fu_773_p2.read()) + sc_bigint<32>(tmp_2_20_fu_782_p1.read()));
}

void array_io::thread_acc_6_loc_assign_1_fu_838_p2() {
    acc_6_loc_assign_1_fu_838_p2 = (!acc_6_loc_assign_2_reg_1223.read().is_01() || !tmp_2_13_fu_834_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_6_loc_assign_2_reg_1223.read()) + sc_bigint<32>(tmp_2_13_fu_834_p1.read()));
}

void array_io::thread_acc_6_loc_assign_2_fu_759_p2() {
    acc_6_loc_assign_2_fu_759_p2 = (!acc_6.read().is_01() || !tmp_2_6_fu_755_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_6.read()) + sc_bigint<32>(tmp_2_6_fu_755_p1.read()));
}

void array_io::thread_acc_6_loc_fu_851_p2() {
    acc_6_loc_fu_851_p2 = (!acc_6_loc_assign_1_fu_838_p2.read().is_01() || !tmp_2_21_fu_847_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_6_loc_assign_1_fu_838_p2.read()) + sc_bigint<32>(tmp_2_21_fu_847_p1.read()));
}

void array_io::thread_acc_7_loc_assign_1_fu_885_p2() {
    acc_7_loc_assign_1_fu_885_p2 = (!acc_7_loc_assign_2_reg_1263.read().is_01() || !tmp_2_14_fu_881_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_7_loc_assign_2_reg_1263.read()) + sc_bigint<32>(tmp_2_14_fu_881_p1.read()));
}

void array_io::thread_acc_7_loc_assign_2_fu_824_p2() {
    acc_7_loc_assign_2_fu_824_p2 = (!acc_7.read().is_01() || !tmp_2_7_fu_820_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(acc_7.read()) + sc_bigint<32>(tmp_2_7_fu_820_p1.read()));
}

void array_io::thread_acc_7_loc_fu_898_p2() {
    acc_7_loc_fu_898_p2 = (!acc_7_loc_assign_1_fu_885_p2.read().is_01() || !tmp_2_22_fu_894_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_7_loc_assign_1_fu_885_p2.read()) + sc_bigint<32>(tmp_2_22_fu_894_p1.read()));
}

void array_io::thread_ap_done() {
    if ((!ap_sig_bdd_115.read() && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void array_io::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void array_io::thread_ap_ready() {
    if ((!ap_sig_bdd_115.read() && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_bdd_106() {
    ap_sig_bdd_106 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void array_io::thread_ap_sig_bdd_115() {
    ap_sig_bdd_115 = (esl_seteq<1,1,1>(d_o_0_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(d_o_1_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(d_o_2_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(d_o_3_full_n.read(), ap_const_logic_0));
}

void array_io::thread_ap_sig_bdd_124() {
    ap_sig_bdd_124 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void array_io::thread_ap_sig_bdd_133() {
    ap_sig_bdd_133 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void array_io::thread_ap_sig_bdd_142() {
    ap_sig_bdd_142 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void array_io::thread_ap_sig_bdd_151() {
    ap_sig_bdd_151 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void array_io::thread_ap_sig_bdd_160() {
    ap_sig_bdd_160 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void array_io::thread_ap_sig_bdd_178() {
    ap_sig_bdd_178 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void array_io::thread_ap_sig_bdd_28() {
    ap_sig_bdd_28 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void array_io::thread_ap_sig_bdd_364() {
    ap_sig_bdd_364 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void array_io::thread_ap_sig_bdd_83() {
    ap_sig_bdd_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void array_io::thread_ap_sig_bdd_90() {
    ap_sig_bdd_90 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void array_io::thread_ap_sig_bdd_98() {
    ap_sig_bdd_98 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void array_io::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_bdd_160.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_bdd_178.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_bdd_364.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_28.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_83.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_bdd_90.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_bdd_98.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_bdd_106.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_bdd_124.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_bdd_133.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_bdd_142.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void array_io::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_bdd_151.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void array_io::thread_d_i_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) {
        d_i_0_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        d_i_0_address0 = "XXXX";
    }
}

void array_io::thread_d_i_0_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_i_0_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else {
        d_i_0_address1 = "XXXX";
    }
}

void array_io::thread_d_i_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
          !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        d_i_0_ce0 = ap_const_logic_1;
    } else {
        d_i_0_ce0 = ap_const_logic_0;
    }
}

void array_io::thread_d_i_0_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())))) {
        d_i_0_ce1 = ap_const_logic_1;
    } else {
        d_i_0_ce1 = ap_const_logic_0;
    }
}

void array_io::thread_d_i_1_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_F);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        d_i_1_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        d_i_1_address0 = "XXXX";
    }
}

void array_io::thread_d_i_1_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_E);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_D);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_C);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_B);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_A);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_9);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        d_i_1_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else {
        d_i_1_address1 = "XXXX";
    }
}

void array_io::thread_d_i_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())))) {
        d_i_1_ce0 = ap_const_logic_1;
    } else {
        d_i_1_ce0 = ap_const_logic_0;
    }
}

void array_io::thread_d_i_1_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())))) {
        d_i_1_ce1 = ap_const_logic_1;
    } else {
        d_i_1_ce1 = ap_const_logic_0;
    }
}

void array_io::thread_d_o_0_din() {
    if (!ap_sig_bdd_115.read()) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            d_o_0_din = tmp_8_reg_1268.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
            d_o_0_din = tmp_7_reg_1228.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
            d_o_0_din = tmp_6_reg_1183.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
            d_o_0_din = tmp_5_reg_1138.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
            d_o_0_din = tmp_4_reg_1093.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            d_o_0_din = tmp_3_reg_1048.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
            d_o_0_din = tmp_1_reg_1003.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            d_o_0_din = tmp_reg_973.read();
        } else {
            d_o_0_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        d_o_0_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void array_io::thread_d_o_0_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())))) {
        d_o_0_write = ap_const_logic_1;
    } else {
        d_o_0_write = ap_const_logic_0;
    }
}

void array_io::thread_d_o_1_din() {
    if (!ap_sig_bdd_115.read()) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            d_o_1_din = tmp_16_reg_1293.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
            d_o_1_din = tmp_15_reg_1273.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
            d_o_1_din = tmp_14_reg_1233.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
            d_o_1_din = tmp_13_reg_1193.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
            d_o_1_din = tmp_12_reg_1148.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            d_o_1_din = tmp_11_reg_1103.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
            d_o_1_din = tmp_10_reg_1058.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            d_o_1_din = tmp_9_reg_1013.read();
        } else {
            d_o_1_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        d_o_1_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void array_io::thread_d_o_1_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())))) {
        d_o_1_write = ap_const_logic_1;
    } else {
        d_o_1_write = ap_const_logic_0;
    }
}

void array_io::thread_d_o_2_din() {
    if (!ap_sig_bdd_115.read()) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            d_o_2_din = tmp_24_reg_1303.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
            d_o_2_din = tmp_23_reg_1283.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
            d_o_2_din = tmp_22_reg_1248.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
            d_o_2_din = tmp_21_reg_1208.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
            d_o_2_din = tmp_20_reg_1163.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            d_o_2_din = tmp_19_reg_1118.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
            d_o_2_din = tmp_18_reg_1073.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            d_o_2_din = tmp_17_reg_1028.read();
        } else {
            d_o_2_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        d_o_2_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void array_io::thread_d_o_2_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())))) {
        d_o_2_write = ap_const_logic_1;
    } else {
        d_o_2_write = ap_const_logic_0;
    }
}

void array_io::thread_d_o_3_din() {
    if (!ap_sig_bdd_115.read()) {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
            d_o_3_din = tmp_32_fu_943_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
            d_o_3_din = tmp_31_fu_923_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
            d_o_3_din = tmp_30_fu_876_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
            d_o_3_din = tmp_29_fu_811_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
            d_o_3_din = tmp_28_fu_746_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
            d_o_3_din = tmp_27_fu_681_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
            d_o_3_din = tmp_26_fu_616_p1.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
            d_o_3_din = tmp_25_fu_551_p1.read();
        } else {
            d_o_3_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
        }
    } else {
        d_o_3_din =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void array_io::thread_d_o_3_write() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
          !ap_sig_bdd_115.read()) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) || 
         (!ap_sig_bdd_115.read() && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())))) {
        d_o_3_write = ap_const_logic_1;
    } else {
        d_o_3_write = ap_const_logic_0;
    }
}

void array_io::thread_temp_1_fu_605_p2() {
    temp_1_fu_605_p2 = (!acc_1_loc_reg_1068.read().is_01() || !tmp_2_24_fu_601_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_1_loc_reg_1068.read()) + sc_bigint<32>(tmp_2_24_fu_601_p1.read()));
}

void array_io::thread_temp_2_fu_670_p2() {
    temp_2_fu_670_p2 = (!acc_2_loc_reg_1113.read().is_01() || !tmp_2_25_fu_666_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_2_loc_reg_1113.read()) + sc_bigint<32>(tmp_2_25_fu_666_p1.read()));
}

void array_io::thread_temp_3_fu_735_p2() {
    temp_3_fu_735_p2 = (!acc_3_loc_reg_1158.read().is_01() || !tmp_2_26_fu_731_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_3_loc_reg_1158.read()) + sc_bigint<32>(tmp_2_26_fu_731_p1.read()));
}

void array_io::thread_temp_4_fu_800_p2() {
    temp_4_fu_800_p2 = (!acc_4_loc_reg_1203.read().is_01() || !tmp_2_27_fu_796_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_4_loc_reg_1203.read()) + sc_bigint<32>(tmp_2_27_fu_796_p1.read()));
}

void array_io::thread_temp_5_fu_865_p2() {
    temp_5_fu_865_p2 = (!acc_5_loc_reg_1243.read().is_01() || !tmp_2_28_fu_861_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_5_loc_reg_1243.read()) + sc_bigint<32>(tmp_2_28_fu_861_p1.read()));
}

void array_io::thread_temp_6_fu_912_p2() {
    temp_6_fu_912_p2 = (!acc_6_loc_reg_1278.read().is_01() || !tmp_2_29_fu_908_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_6_loc_reg_1278.read()) + sc_bigint<32>(tmp_2_29_fu_908_p1.read()));
}

void array_io::thread_temp_7_fu_932_p2() {
    temp_7_fu_932_p2 = (!acc_7_loc_reg_1298.read().is_01() || !tmp_2_30_fu_928_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_7_loc_reg_1298.read()) + sc_bigint<32>(tmp_2_30_fu_928_p1.read()));
}

void array_io::thread_temp_s_fu_540_p2() {
    temp_s_fu_540_p2 = (!acc_0_loc_reg_1023.read().is_01() || !tmp_2_23_fu_536_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(acc_0_loc_reg_1023.read()) + sc_bigint<32>(tmp_2_23_fu_536_p1.read()));
}

void array_io::thread_tmp_10_fu_518_p1() {
    tmp_10_fu_518_p1 = acc_1_loc_assign_1_fu_513_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_11_fu_583_p1() {
    tmp_11_fu_583_p1 = acc_2_loc_assign_1_fu_578_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_12_fu_648_p1() {
    tmp_12_fu_648_p1 = acc_3_loc_assign_1_fu_643_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_13_fu_713_p1() {
    tmp_13_fu_713_p1 = acc_4_loc_assign_1_fu_708_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_14_fu_778_p1() {
    tmp_14_fu_778_p1 = acc_5_loc_assign_1_fu_773_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_15_fu_843_p1() {
    tmp_15_fu_843_p1 = acc_6_loc_assign_1_fu_838_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_16_fu_890_p1() {
    tmp_16_fu_890_p1 = acc_7_loc_assign_1_fu_885_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_17_fu_487_p1() {
    tmp_17_fu_487_p1 = acc_0_loc_fu_481_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_18_fu_532_p1() {
    tmp_18_fu_532_p1 = acc_1_loc_fu_526_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_19_fu_597_p1() {
    tmp_19_fu_597_p1 = acc_2_loc_fu_591_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_1_fu_460_p1() {
    tmp_1_fu_460_p1 = acc_1_loc_assign_2_fu_454_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_20_fu_662_p1() {
    tmp_20_fu_662_p1 = acc_3_loc_fu_656_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_21_fu_727_p1() {
    tmp_21_fu_727_p1 = acc_4_loc_fu_721_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_22_fu_792_p1() {
    tmp_22_fu_792_p1 = acc_5_loc_fu_786_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_23_fu_857_p1() {
    tmp_23_fu_857_p1 = acc_6_loc_fu_851_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_24_fu_904_p1() {
    tmp_24_fu_904_p1 = acc_7_loc_fu_898_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_25_fu_551_p1() {
    tmp_25_fu_551_p1 = temp_s_fu_540_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_26_fu_616_p1() {
    tmp_26_fu_616_p1 = temp_1_fu_605_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_27_fu_681_p1() {
    tmp_27_fu_681_p1 = temp_2_fu_670_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_28_fu_746_p1() {
    tmp_28_fu_746_p1 = temp_3_fu_735_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_29_fu_811_p1() {
    tmp_29_fu_811_p1 = temp_4_fu_800_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_2_10_fu_639_p1() {
    tmp_2_10_fu_639_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_11_fu_704_p1() {
    tmp_2_11_fu_704_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_12_fu_769_p1() {
    tmp_2_12_fu_769_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_13_fu_834_p1() {
    tmp_2_13_fu_834_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_14_fu_881_p1() {
    tmp_2_14_fu_881_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_15_fu_477_p1() {
    tmp_2_15_fu_477_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_16_fu_522_p1() {
    tmp_2_16_fu_522_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_17_fu_587_p1() {
    tmp_2_17_fu_587_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_18_fu_652_p1() {
    tmp_2_18_fu_652_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_19_fu_717_p1() {
    tmp_2_19_fu_717_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_1_fu_450_p1() {
    tmp_2_1_fu_450_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_20_fu_782_p1() {
    tmp_2_20_fu_782_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_21_fu_847_p1() {
    tmp_2_21_fu_847_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_22_fu_894_p1() {
    tmp_2_22_fu_894_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_23_fu_536_p1() {
    tmp_2_23_fu_536_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_24_fu_601_p1() {
    tmp_2_24_fu_601_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_25_fu_666_p1() {
    tmp_2_25_fu_666_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_26_fu_731_p1() {
    tmp_2_26_fu_731_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_27_fu_796_p1() {
    tmp_2_27_fu_796_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_28_fu_861_p1() {
    tmp_2_28_fu_861_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_29_fu_908_p1() {
    tmp_2_29_fu_908_p1 = esl_sext<32,16>(reg_424.read());
}

void array_io::thread_tmp_2_2_fu_495_p1() {
    tmp_2_2_fu_495_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_30_fu_928_p1() {
    tmp_2_30_fu_928_p1 = esl_sext<32,16>(reg_420.read());
}

void array_io::thread_tmp_2_3_fu_560_p1() {
    tmp_2_3_fu_560_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_4_fu_625_p1() {
    tmp_2_4_fu_625_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_5_fu_690_p1() {
    tmp_2_5_fu_690_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_6_fu_755_p1() {
    tmp_2_6_fu_755_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_7_fu_820_p1() {
    tmp_2_7_fu_820_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_8_fu_464_p1() {
    tmp_2_8_fu_464_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_9_fu_509_p1() {
    tmp_2_9_fu_509_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_2_fu_432_p1() {
    tmp_2_fu_432_p1 = esl_sext<32,16>(reg_412.read());
}

void array_io::thread_tmp_2_s_fu_574_p1() {
    tmp_2_s_fu_574_p1 = esl_sext<32,16>(reg_416.read());
}

void array_io::thread_tmp_30_fu_876_p1() {
    tmp_30_fu_876_p1 = temp_5_fu_865_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_31_fu_923_p1() {
    tmp_31_fu_923_p1 = temp_6_fu_912_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_32_fu_943_p1() {
    tmp_32_fu_943_p1 = temp_7_fu_932_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_3_fu_505_p1() {
    tmp_3_fu_505_p1 = acc_2_loc_assign_2_fu_499_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_4_fu_570_p1() {
    tmp_4_fu_570_p1 = acc_3_loc_assign_2_fu_564_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_5_fu_635_p1() {
    tmp_5_fu_635_p1 = acc_4_loc_assign_2_fu_629_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_6_fu_700_p1() {
    tmp_6_fu_700_p1 = acc_5_loc_assign_2_fu_694_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_7_fu_765_p1() {
    tmp_7_fu_765_p1 = acc_6_loc_assign_2_fu_759_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_8_fu_830_p1() {
    tmp_8_fu_830_p1 = acc_7_loc_assign_2_fu_824_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_9_fu_473_p1() {
    tmp_9_fu_473_p1 = acc_0_loc_assign_1_fu_468_p2.read().range(16-1, 0);
}

void array_io::thread_tmp_fu_442_p1() {
    tmp_fu_442_p1 = acc_0_loc_assign_2_fu_436_p2.read().range(16-1, 0);
}

void array_io::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 32 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            }
            break;
        case 64 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            }
            break;
        case 128 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 256 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 512 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else {
                ap_NS_fsm = ap_ST_st10_fsm_9;
            }
            break;
        case 1024 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 2048 : 
            if (!ap_sig_bdd_115.read()) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

void array_io::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_0_din\" :  \"" << d_o_0_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_o_0_full_n\" :  \"" << d_o_0_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_0_write\" :  \"" << d_o_0_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_1_din\" :  \"" << d_o_1_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_o_1_full_n\" :  \"" << d_o_1_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_1_write\" :  \"" << d_o_1_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_2_din\" :  \"" << d_o_2_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_o_2_full_n\" :  \"" << d_o_2_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_2_write\" :  \"" << d_o_2_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_3_din\" :  \"" << d_o_3_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_o_3_full_n\" :  \"" << d_o_3_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_o_3_write\" :  \"" << d_o_3_write.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_0_address0\" :  \"" << d_i_0_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_0_ce0\" :  \"" << d_i_0_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_i_0_q0\" :  \"" << d_i_0_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_0_address1\" :  \"" << d_i_0_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_0_ce1\" :  \"" << d_i_0_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_i_0_q1\" :  \"" << d_i_0_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_1_address0\" :  \"" << d_i_1_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_1_ce0\" :  \"" << d_i_1_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_i_1_q0\" :  \"" << d_i_1_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_1_address1\" :  \"" << d_i_1_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"d_i_1_ce1\" :  \"" << d_i_1_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"d_i_1_q1\" :  \"" << d_i_1_q1.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

