// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _duc_mixer_HH_
#define _duc_mixer_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "duc_ama_addmuladd_18s_18s_16s_32s_32_3.h"
#include "duc_ama_submuladd_18s_18s_16s_32s_32_3.h"
#include "duc_am_submul_16s_16s_18s_32_4.h"
#include "duc_mixer_DI_cache.h"
#include "duc_mixer_dds_table.h"

namespace ap_rtl {

struct duc_mixer : public sc_module {
    // Port declarations 12
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > freq;
    sc_in< sc_lv<18> > Din;
    sc_out< sc_lv<18> > Dout_I;
    sc_out< sc_logic > Dout_I_ap_vld;
    sc_out< sc_lv<18> > Dout_Q;
    sc_out< sc_logic > Dout_Q_ap_vld;


    // Module declarations
    duc_mixer(sc_module_name name);
    SC_HAS_PROCESS(duc_mixer);

    ~duc_mixer();

    sc_trace_file* mVcdFile;

    duc_mixer_DI_cache* DI_cache_U;
    duc_mixer_dds_table* dds_table_U;
    duc_ama_addmuladd_18s_18s_16s_32s_32_3<1,3,18,18,16,32,32>* duc_ama_addmuladd_18s_18s_16s_32s_32_3_U9;
    duc_ama_submuladd_18s_18s_16s_32s_32_3<1,3,18,18,16,32,32>* duc_ama_submuladd_18s_18s_16s_32s_32_3_U10;
    duc_am_submul_16s_16s_18s_32_4<1,4,16,16,18,32>* duc_am_submul_16s_16s_18s_32_4_U11;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_28;
    sc_signal< sc_lv<3> > i_1;
    sc_signal< sc_lv<1> > init_1;
    sc_signal< sc_lv<1> > ch_1;
    sc_signal< sc_lv<4> > index;
    sc_signal< sc_lv<4> > DI_cache_address0;
    sc_signal< sc_logic > DI_cache_ce0;
    sc_signal< sc_logic > DI_cache_we0;
    sc_signal< sc_lv<18> > DI_cache_d0;
    sc_signal< sc_lv<18> > DI_cache_q0;
    sc_signal< sc_lv<16> > acc;
    sc_signal< sc_lv<5> > dds_table_address0;
    sc_signal< sc_logic > dds_table_ce0;
    sc_signal< sc_lv<16> > dds_table_q0;
    sc_signal< sc_lv<5> > dds_table_address1;
    sc_signal< sc_logic > dds_table_ce1;
    sc_signal< sc_lv<16> > dds_table_q1;
    sc_signal< sc_lv<3> > i_1_load_reg_367;
    sc_signal< sc_lv<3> > inc_fu_142_p2;
    sc_signal< sc_lv<3> > inc_reg_372;
    sc_signal< sc_lv<1> > valid_in_fu_158_p2;
    sc_signal< sc_lv<1> > valid_in_reg_377;
    sc_signal< sc_lv<1> > ch_1_load_reg_381;
    sc_signal< sc_lv<1> > brmerge_demorgan_fu_180_p2;
    sc_signal< sc_lv<1> > brmerge_demorgan_reg_386;
    sc_signal< sc_lv<4> > index_load_reg_390;
    sc_signal< sc_lv<5> > phase1_reg_398;
    sc_signal< sc_lv<5> > phase2_fu_221_p2;
    sc_signal< sc_lv<5> > phase2_reg_404;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_100;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_109;
    sc_signal< sc_lv<16> > sine_reg_419;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_119;
    sc_signal< sc_lv<16> > cosine_reg_425;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_129;
    sc_signal< sc_lv<18> > Din_re_reg_441;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_139;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_148;
    sc_signal< sc_lv<32> > grp_fu_353_p3;
    sc_signal< sc_lv<32> > tmp_2_reg_456;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_159;
    sc_signal< sc_lv<32> > grp_fu_344_p4;
    sc_signal< sc_lv<32> > tmp_8_reg_462;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_168;
    sc_signal< sc_lv<32> > grp_fu_335_p4;
    sc_signal< sc_lv<32> > tmp_4_reg_467;
    sc_signal< sc_lv<64> > tmp_fu_216_p1;
    sc_signal< sc_lv<64> > tmp_i_fu_226_p1;
    sc_signal< sc_lv<64> > tmp_61_i_fu_230_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_234_p1;
    sc_signal< sc_lv<3> > inc_1_fu_322_p3;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_185;
    sc_signal< sc_lv<1> > tmp_9_fu_279_p2;
    sc_signal< sc_lv<1> > tmp_11_fu_295_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_290_p2;
    sc_signal< sc_lv<4> > tmp_12_fu_306_p2;
    sc_signal< sc_lv<16> > acc_assign_i_fu_194_p2;
    sc_signal< sc_lv<2> > tmp_14_fu_148_p4;
    sc_signal< sc_lv<16> > freq_dds_fu_168_p3;
    sc_signal< sc_lv<1> > tmp_13_fu_317_p2;
    sc_signal< sc_lv<18> > grp_fu_335_p0;
    sc_signal< sc_lv<19> > tmp_i6_fu_250_p1;
    sc_signal< sc_lv<18> > grp_fu_335_p1;
    sc_signal< sc_lv<19> > tmp_i5_fu_247_p1;
    sc_signal< sc_lv<16> > grp_fu_335_p2;
    sc_signal< sc_lv<32> > grp_fu_335_p3;
    sc_signal< sc_lv<18> > grp_fu_344_p0;
    sc_signal< sc_lv<18> > grp_fu_344_p1;
    sc_signal< sc_lv<16> > grp_fu_344_p2;
    sc_signal< sc_lv<32> > grp_fu_344_p3;
    sc_signal< sc_lv<16> > grp_fu_353_p0;
    sc_signal< sc_lv<16> > grp_fu_353_p1;
    sc_signal< sc_lv<18> > grp_fu_353_p2;
    sc_signal< sc_logic > grp_fu_335_ce;
    sc_signal< sc_logic > grp_fu_344_ce;
    sc_signal< sc_logic > grp_fu_353_ce;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_st1_fsm_0;
    static const sc_lv<10> ap_ST_st2_fsm_1;
    static const sc_lv<10> ap_ST_st3_fsm_2;
    static const sc_lv<10> ap_ST_st4_fsm_3;
    static const sc_lv<10> ap_ST_st5_fsm_4;
    static const sc_lv<10> ap_ST_st6_fsm_5;
    static const sc_lv<10> ap_ST_st7_fsm_6;
    static const sc_lv<10> ap_ST_st8_fsm_7;
    static const sc_lv<10> ap_ST_st9_fsm_8;
    static const sc_lv<10> ap_ST_st10_fsm_9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<5> ap_const_lv5_8;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_5;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_DI_cache_address0();
    void thread_DI_cache_ce0();
    void thread_DI_cache_d0();
    void thread_DI_cache_we0();
    void thread_Dout_I();
    void thread_Dout_I_ap_vld();
    void thread_Dout_Q();
    void thread_Dout_Q_ap_vld();
    void thread_acc_assign_i_fu_194_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_100();
    void thread_ap_sig_bdd_109();
    void thread_ap_sig_bdd_119();
    void thread_ap_sig_bdd_129();
    void thread_ap_sig_bdd_139();
    void thread_ap_sig_bdd_148();
    void thread_ap_sig_bdd_159();
    void thread_ap_sig_bdd_168();
    void thread_ap_sig_bdd_185();
    void thread_ap_sig_bdd_28();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_brmerge_demorgan_fu_180_p2();
    void thread_dds_table_address0();
    void thread_dds_table_address1();
    void thread_dds_table_ce0();
    void thread_dds_table_ce1();
    void thread_freq_dds_fu_168_p3();
    void thread_grp_fu_335_ce();
    void thread_grp_fu_335_p0();
    void thread_grp_fu_335_p1();
    void thread_grp_fu_335_p2();
    void thread_grp_fu_335_p3();
    void thread_grp_fu_344_ce();
    void thread_grp_fu_344_p0();
    void thread_grp_fu_344_p1();
    void thread_grp_fu_344_p2();
    void thread_grp_fu_344_p3();
    void thread_grp_fu_353_ce();
    void thread_grp_fu_353_p0();
    void thread_grp_fu_353_p1();
    void thread_grp_fu_353_p2();
    void thread_inc_1_fu_322_p3();
    void thread_inc_fu_142_p2();
    void thread_phase2_fu_221_p2();
    void thread_tmp_10_fu_290_p2();
    void thread_tmp_11_fu_295_p2();
    void thread_tmp_12_fu_306_p2();
    void thread_tmp_13_fu_317_p2();
    void thread_tmp_14_fu_148_p4();
    void thread_tmp_61_i_fu_230_p1();
    void thread_tmp_9_fu_279_p2();
    void thread_tmp_fu_216_p1();
    void thread_tmp_i5_fu_247_p1();
    void thread_tmp_i6_fu_250_p1();
    void thread_tmp_i_fu_226_p1();
    void thread_tmp_s_fu_234_p1();
    void thread_valid_in_fu_158_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
